// Backend Phase 12 — code implementations of the governed metrics. Each
// definition is declarative (table, date column, aggregation, fixed
// conditions, allowed dimensions) so the semantic query service can build
// parameterized SQL from it and validate every requested dimension/filter
// against a whitelist. The registry (DB) versions these definitions; a
// published version is immutable. Values are computed only from warehouse
// facts — never by AI.

// Conditions: [column, op, value] — op in = != in notin null notnull < <= > >=
// "$today" resolves to the organization's local business date.
const OPEN_TICKET = ["isOpen", "=", true];

const COMMON_DIMS = { owner: "ownerMembershipId", team: "team", department: "department" };

export const TABLES = {
  analytics_fact_leads: { date: "businessDate", deleted: true, sourceModule: "leads", dims: { ...COMMON_DIMS, status: "status", source: "source", lifecycle_stage: "lifecycleStage", country: "country" }, filterable: ["status", "source", "lifecycleStage", "country", "ownerMembershipId", "team"], drill: { module: "leads", path: "/crm/leads/:id" } },
  analytics_fact_activities: { date: "businessDate", deleted: true, sourceModule: "activities", assignedColumn: "assignedMembershipId", dims: { ...COMMON_DIMS, type: "type", status: "status" }, filterable: ["type", "status", "ownerMembershipId", "team"], drill: { module: "activities", path: "/crm/activities" } },
  analytics_fact_deal_events: { date: "businessDate", deleted: false, sourceModule: "deals", dims: { ...COMMON_DIMS, stage: "toStage", event_type: "eventType" }, filterable: ["toStage", "eventType", "ownerMembershipId", "team"], drill: { module: "deals", path: "/crm/deals/:id", idColumn: "dealId" } },
  analytics_fact_deal_snapshots: { date: "snapshotDate", deleted: false, snapshot: true, sourceModule: "deals", money: { amount: "amount", base: "baseAmount" }, dims: { ...COMMON_DIMS, stage: "stage", status: "status", pipeline: "pipelineId", currency: "currency" }, filterable: ["stage", "status", "pipelineId", "currency", "ownerMembershipId", "team"], drill: { module: "deals", path: "/crm/deals/:id", idColumn: "dealId" } },
  analytics_fact_quotes: { date: "businessDate", deleted: true, sourceModule: "quotes", money: { amount: "amount", base: "baseAmount" }, dims: { ...COMMON_DIMS, status: "status", currency: "currency" }, filterable: ["status", "currency", "ownerMembershipId", "team"], drill: { module: "quotes", path: "/sales/quotes/:id" } },
  analytics_fact_orders: { date: "businessDate", deleted: true, sourceModule: "orders", money: { amount: "amount", base: "baseAmount" }, dims: { ...COMMON_DIMS, status: "status", order_type: "orderType", currency: "currency" }, filterable: ["status", "orderType", "currency", "ownerMembershipId", "team"], drill: { module: "orders", path: "/sales/orders/:id" } },
  analytics_fact_contracts: { date: "endDate", deleted: true, sourceModule: "contracts", money: { amount: "amount", base: "baseAmount" }, dims: { ...COMMON_DIMS, status: "status", contract_type: "contractType", currency: "currency" }, filterable: ["status", "contractType", "currency", "ownerMembershipId", "team"], drill: { module: "contracts", path: "/sales/contracts/:id" } },
  analytics_fact_support: { date: "businessDate", deleted: true, sourceModule: "tickets", assignedColumn: "assignedMembershipId", dims: { ...COMMON_DIMS, status: "status", priority: "priority", queue: "queueId" }, filterable: ["status", "priority", "queueId", "ownerMembershipId", "team", "department"], drill: { module: "tickets", path: "/support/tickets/:id" } },
  analytics_fact_projects: { date: "businessDate", deleted: true, sourceModule: "projects", dims: { ...COMMON_DIMS, status: "status", health: "healthState", priority: "priority" }, filterable: ["status", "healthState", "priority", "ownerMembershipId", "team", "department"], drill: { module: "projects", path: "/projects/:id/overview" } },
  analytics_fact_tasks: { date: "businessDate", deleted: true, sourceModule: "projects", dims: { owner: "ownerMembershipId", status: "status", status_category: "statusCategory", project: "projectId" }, filterable: ["status", "statusCategory", "projectId", "ownerMembershipId"], drill: { module: "tasks", path: "/projects/tasks" } },
  analytics_fact_time: { date: "businessDate", deleted: true, sourceModule: "projects", dims: { owner: "ownerMembershipId", project: "projectId", billable: "billable" }, filterable: ["projectId", "billable", "ownerMembershipId"], drill: null },
  analytics_fact_invoices: { date: "businessDate", deleted: true, sourceModule: "invoices", money: { amount: "amount", base: "baseAmount" }, dims: { owner: "ownerMembershipId", status: "status", currency: "currency" }, filterable: ["status", "currency", "ownerMembershipId"], drill: { module: "invoices", path: "/finance/invoices/:id" } },
  analytics_fact_payments: { date: "businessDate", deleted: true, sourceModule: "payments", money: { amount: "amount", base: "baseAmount" }, dims: { owner: "ownerMembershipId", method: "method", direction: "direction", currency: "currency" }, filterable: ["method", "direction", "currency", "ownerMembershipId"], drill: { module: "payments", path: "/finance/payments" } },
  analytics_fact_expenses: { date: "businessDate", deleted: true, sourceModule: "expenses", money: { amount: "amount", base: "baseAmount" }, dims: { owner: "ownerMembershipId", category: "category", status: "status", currency: "currency" }, filterable: ["category", "status", "currency", "ownerMembershipId"], drill: { module: "expenses", path: "/finance/expenses" } },
  analytics_fact_budgets: { date: "snapshotDate", deleted: false, snapshot: true, sourceModule: "budgets", orgOnly: true, dims: { budget: "budgetName", department: "department", currency: "currency" }, filterable: ["department", "currency"], drill: null },
  analytics_fact_ai_usage: { date: "businessDate", deleted: false, sourceModule: "ai_usage", dims: { owner: "ownerMembershipId", capability: "capabilityKey", provider: "providerKey", model: "modelId", outcome: "outcome", use_case: "useCaseKey" }, filterable: ["capabilityKey", "providerKey", "modelId", "outcome", "useCaseKey", "ownerMembershipId"], drill: null },
  analytics_fact_ai_events: { date: "businessDate", deleted: false, sourceModule: "ai_usage", dims: { owner: "ownerMembershipId", kind: "kind", status: "status", category: "category", severity: "severity" }, filterable: ["kind", "status", "category", "severity", "capabilityKey"], drill: null },
  analytics_fact_snapshots: { date: "snapshotDate", deleted: false, snapshot: true, sourceModule: null, dims: { owner: "ownerMembershipId", team: "team", department: "department", key: "key", currency: "currency" }, filterable: ["ownerMembershipId", "team", "department", "currency"], drill: null },
};

const def = (key, o) => ({ key, freshnessTargetMinutes: 60, sensitivity: "basic", nullBehavior: "Zero when no rows match", ...o });

export const METRICS = [
  // Sales
  def("leads_created", { name: "Leads created", module: "analytics_sales", unit: "count", table: "analytics_fact_leads", agg: "count", additivity: "additive", definition: "Leads created in the period (organization business date).", formula: "COUNT(leads) WHERE createdDate IN period AND NOT archived", sources: ["leads"] }),
  def("leads_qualified", { name: "Qualified leads", module: "analytics_sales", unit: "count", table: "analytics_fact_leads", agg: "count", where: [["qualified", "=", true]], additivity: "additive", definition: "Leads created in the period that are qualified or converted.", formula: "COUNT(leads) WHERE qualified", sources: ["leads"] }),
  def("leads_converted", { name: "Leads converted", module: "analytics_sales", unit: "count", table: "analytics_fact_leads", agg: "count", dateColumn: "convertedDate", where: [["converted", "=", true]], additivity: "additive", definition: "Leads converted to a deal in the period (by conversion date).", formula: "COUNT(leads) WHERE convertedDate IN period", sources: ["leads"] }),
  def("lead_conversion_rate", { name: "Lead conversion rate", module: "analytics_sales", unit: "percent", agg: "ratio", numerator: "leads_converted", denominator: "leads_created", additivity: "non-additive", definition: "Leads converted in the period divided by leads created in the period.", formula: "leads_converted / leads_created", sources: ["leads"] }),
  def("deals_created", { name: "Deals created", module: "analytics_sales", unit: "count", table: "analytics_fact_deal_events", agg: "count", where: [["eventType", "=", "created"]], additivity: "additive", definition: "Deals created in the period.", formula: "COUNT(deal events) WHERE type = created", sources: ["deal_events"] }),
  def("deals_won", { name: "Deals won", module: "analytics_sales", unit: "count", table: "analytics_fact_deal_events", agg: "count_distinct", column: "dealId", where: [["eventType", "=", "won"]], additivity: "non-additive", definition: "Distinct deals that moved into a Won stage in the period.", formula: "COUNT DISTINCT deal WHERE moved to Won stage", sources: ["deal_events"] }),
  def("deals_lost", { name: "Deals lost", module: "analytics_sales", unit: "count", table: "analytics_fact_deal_events", agg: "count_distinct", column: "dealId", where: [["eventType", "=", "lost"]], additivity: "non-additive", definition: "Distinct deals that moved into a Lost stage in the period.", formula: "COUNT DISTINCT deal WHERE moved to Lost stage", sources: ["deal_events"] }),
  def("win_rate", { name: "Win rate", module: "analytics_sales", unit: "percent", agg: "ratio", numerator: "deals_won", denominator: "deals_closed", additivity: "non-additive", definition: "Won deals divided by won plus lost deals closed in the period.", formula: "deals_won / (deals_won + deals_lost)", sources: ["deal_events"] }),
  def("deals_closed", { name: "Deals closed", module: "analytics_sales", unit: "count", table: "analytics_fact_deal_events", agg: "count_distinct", column: "dealId", where: [["eventType", "in", ["won", "lost"]]], additivity: "non-additive", definition: "Distinct deals that moved into a Won or Lost stage in the period.", formula: "COUNT DISTINCT deal WHERE moved to Won or Lost", sources: ["deal_events"] }),
  def("pipeline_value", { name: "Open pipeline value", module: "analytics_sales", unit: "currency", table: "analytics_fact_deal_snapshots", agg: "sum", column: "amount", money: true, snapshot: true, where: [["isOpen", "=", true]], additivity: "semi-additive", definition: "Total value of open deals on the last snapshot date in the period (not summed across days).", formula: "SUM(open deal amount) AT last snapshot in period", sources: ["deal_snapshots"], freshnessTargetMinutes: 1440 }),
  def("weighted_pipeline", { name: "Weighted pipeline", module: "analytics_sales", unit: "currency", table: "analytics_fact_deal_snapshots", agg: "sum", column: "weightedAmount", baseColumn: "baseWeightedAmount", money: true, snapshot: true, where: [["isOpen", "=", true]], additivity: "semi-additive", definition: "Open deal value × stage probability on the last snapshot date in the period.", formula: "SUM(amount × probability / 100) AT last snapshot", sources: ["deal_snapshots"], freshnessTargetMinutes: 1440 }),
  def("open_deals", { name: "Open deals", module: "analytics_sales", unit: "count", table: "analytics_fact_deal_snapshots", agg: "count", snapshot: true, where: [["isOpen", "=", true]], additivity: "semi-additive", definition: "Open deals on the last snapshot date in the period.", formula: "COUNT(open deals) AT last snapshot", sources: ["deal_snapshots"], freshnessTargetMinutes: 1440 }),
  def("deals_without_next_action", { name: "Open deals without next action", module: "analytics_sales", unit: "count", table: "analytics_fact_deal_snapshots", agg: "count", snapshot: true, where: [["isOpen", "=", true], ["hasNextAction", "=", false]], additivity: "semi-additive", definition: "Open deals with no next action recorded, on the last snapshot date.", formula: "COUNT(open deals) WHERE next action empty", sources: ["deal_snapshots"], freshnessTargetMinutes: 1440 }),
  def("quotes_value", { name: "Quoted value", module: "analytics_sales", unit: "currency", table: "analytics_fact_quotes", agg: "sum", column: "amount", money: true, additivity: "additive", definition: "Grand total of quotes issued in the period.", formula: "SUM(quote grand total) WHERE issued in period", sources: ["quotes"] }),
  def("quotes_accepted", { name: "Quotes accepted", module: "analytics_sales", unit: "count", table: "analytics_fact_quotes", agg: "count", where: [["acceptedAt", "notnull"]], additivity: "additive", definition: "Quotes issued in the period that were accepted.", formula: "COUNT(quotes) WHERE accepted", sources: ["quotes"] }),
  def("orders_value", { name: "Order value", module: "analytics_sales", unit: "currency", table: "analytics_fact_orders", agg: "sum", column: "amount", money: true, where: [["status", "notin", ["Cancelled", "Draft"]]], additivity: "additive", definition: "Grand total of non-draft, non-cancelled orders dated in the period.", formula: "SUM(order grand total)", sources: ["orders"] }),
  def("renewal_exposure", { name: "Contracts ending", module: "analytics_sales", unit: "currency", table: "analytics_fact_contracts", agg: "sum", column: "amount", money: true, where: [["status", "in", ["Active", "Signed", "Expiring"]]], additivity: "additive", definition: "Value of active contracts whose end date falls in the period.", formula: "SUM(contract value) WHERE endDate IN period", sources: ["contracts"] }),

  // Activities
  def("activities_created", { name: "Activities created", module: "analytics_activities", unit: "count", table: "analytics_fact_activities", agg: "count", additivity: "additive", definition: "Activities created in the period.", formula: "COUNT(activities)", sources: ["activities"] }),
  def("activities_completed", { name: "Activities completed", module: "analytics_activities", unit: "count", table: "analytics_fact_activities", agg: "count", dateColumn: "completedDate", where: [["completedAt", "notnull"]], additivity: "additive", definition: "Activities completed in the period (by completion date).", formula: "COUNT(activities) WHERE completedDate IN period", sources: ["activities"] }),
  def("activities_overdue", { name: "Overdue activities", module: "analytics_activities", unit: "count", table: "analytics_fact_activities", agg: "count", current: true, where: [["completedAt", "null"], ["status", "notin", ["Cancelled", "Completed"]], ["dueDate", "<", "$today"]], additivity: "non-additive", definition: "Open activities past their due date as of today.", formula: "COUNT(activities) WHERE not completed AND dueDate < today", sources: ["activities"] }),
  def("activity_completion_rate", { name: "Activity completion rate", module: "analytics_activities", unit: "percent", agg: "ratio", numerator: "activities_completed", denominator: "activities_created", additivity: "non-additive", definition: "Activities completed in the period divided by activities created in the period.", formula: "activities_completed / activities_created", sources: ["activities"] }),

  // Support
  def("tickets_created", { name: "Tickets created", module: "analytics_support", unit: "count", table: "analytics_fact_support", agg: "count", additivity: "additive", definition: "Support tickets created in the period.", formula: "COUNT(tickets)", sources: ["support"] }),
  def("tickets_resolved", { name: "Tickets resolved", module: "analytics_support", unit: "count", table: "analytics_fact_support", agg: "count", dateColumn: "resolvedDate", where: [["resolvedAt", "notnull"]], additivity: "additive", definition: "Tickets resolved in the period (by resolution date).", formula: "COUNT(tickets) WHERE resolvedDate IN period", sources: ["support"] }),
  def("open_tickets", { name: "Open tickets", module: "analytics_support", unit: "count", table: "analytics_fact_support", agg: "count", current: true, where: [OPEN_TICKET], additivity: "non-additive", definition: "Tickets currently open (not resolved, closed or cancelled).", formula: "COUNT(tickets) WHERE open", sources: ["support"] }),
  def("avg_first_response_minutes", { name: "Average first response", module: "analytics_support", unit: "minutes", table: "analytics_fact_support", agg: "avg", column: "firstResponseMinutes", where: [["firstResponseMinutes", "notnull"]], additivity: "non-additive", definition: "Mean minutes from creation to first response, for tickets created in the period that were responded to.", formula: "AVG(firstRespondedAt − createdAt)", sources: ["support"], nullBehavior: "No value when no ticket has a response" }),
  def("avg_resolution_minutes", { name: "Average resolution time", module: "analytics_support", unit: "minutes", table: "analytics_fact_support", agg: "avg", column: "resolutionMinutes", dateColumn: "resolvedDate", where: [["resolutionMinutes", "notnull"]], additivity: "non-additive", definition: "Mean minutes from creation to resolution for tickets resolved in the period.", formula: "AVG(resolvedAt − createdAt)", sources: ["support"], nullBehavior: "No value when nothing was resolved" }),
  def("sla_response_breaches", { name: "Response SLA breaches", module: "analytics_support", unit: "count", table: "analytics_fact_support", agg: "count", where: [["responseBreached", "=", true]], additivity: "additive", definition: "Tickets created in the period whose first response missed the SLA deadline.", formula: "COUNT(tickets) WHERE response breached", sources: ["support"] }),
  def("sla_response_tracked", { name: "Tickets with a response SLA", module: "analytics_support", unit: "count", table: "analytics_fact_support", agg: "count", where: [["responseBreached", "notnull"]], additivity: "additive", definition: "Tickets created in the period that carry a response SLA deadline.", formula: "COUNT(tickets) WHERE response deadline set", sources: ["support"] }),
  def("sla_response_breach_rate", { name: "Response SLA breach rate", module: "analytics_support", unit: "percent", agg: "ratio", numerator: "sla_response_breaches", denominator: "sla_response_tracked", additivity: "non-additive", definition: "Share of SLA-tracked tickets whose first response was late.", formula: "sla_response_breaches / sla_response_tracked", sources: ["support"] }),
  def("reopened_tickets", { name: "Reopened tickets", module: "analytics_support", unit: "count", table: "analytics_fact_support", agg: "count", where: [["reopenCount", ">", 0]], additivity: "additive", definition: "Tickets created in the period that were reopened at least once.", formula: "COUNT(tickets) WHERE reopenCount > 0", sources: ["support"] }),

  // Projects
  def("active_projects", { name: "Active projects", module: "analytics_projects", unit: "count", table: "analytics_fact_projects", agg: "count", current: true, where: [["status", "notin", ["Completed", "Cancelled", "Archived"]]], additivity: "non-additive", definition: "Projects currently not completed or cancelled.", formula: "COUNT(projects) WHERE active", sources: ["projects"] }),
  def("projects_at_risk", { name: "Projects at risk", module: "analytics_projects", unit: "count", table: "analytics_fact_projects", agg: "count", current: true, where: [["status", "notin", ["Completed", "Cancelled", "Archived"]], ["healthState", "in", ["At Risk", "Off Track", "Red", "Amber"]]], additivity: "non-additive", definition: "Active projects whose health is at risk or off track.", formula: "COUNT(active projects) WHERE health at risk", sources: ["projects"] }),
  def("tasks_completed", { name: "Tasks completed", module: "analytics_projects", unit: "count", table: "analytics_fact_tasks", agg: "count", dateColumn: "completedDate", where: [["completedAt", "notnull"]], additivity: "additive", definition: "Tasks completed in the period.", formula: "COUNT(tasks) WHERE completedDate IN period", sources: ["tasks"] }),
  def("tasks_overdue", { name: "Overdue tasks", module: "analytics_projects", unit: "count", table: "analytics_fact_tasks", agg: "count", current: true, where: [["completedAt", "null"], ["statusCategory", "!=", "Done"], ["dueDate", "<", "$today"]], additivity: "non-additive", definition: "Open tasks past their due date as of today.", formula: "COUNT(tasks) WHERE open AND dueDate < today", sources: ["tasks"] }),
  def("hours_logged", { name: "Hours logged", module: "analytics_projects", unit: "hours", table: "analytics_fact_time", agg: "sum", column: "durationMinutes", scale: 1 / 60, additivity: "additive", definition: "Time entries logged for work dates in the period, in hours.", formula: "SUM(duration minutes) / 60", sources: ["time"] }),
  def("billable_hours", { name: "Billable hours", module: "analytics_projects", unit: "hours", table: "analytics_fact_time", agg: "sum", column: "durationMinutes", scale: 1 / 60, where: [["billable", "=", true]], additivity: "additive", definition: "Billable time logged for work dates in the period, in hours.", formula: "SUM(billable duration minutes) / 60", sources: ["time"] }),
  def("billable_ratio", { name: "Billable ratio", module: "analytics_projects", unit: "percent", agg: "ratio", numerator: "billable_hours", denominator: "hours_logged", additivity: "non-additive", definition: "Billable hours divided by all hours logged in the period.", formula: "billable_hours / hours_logged", sources: ["time"] }),

  // Finance (operational reporting, not audited statements)
  def("invoiced_amount", { name: "Invoiced", module: "analytics_finance", unit: "currency", table: "analytics_fact_invoices", agg: "sum", column: "amount", money: true, where: [["status", "!=", "Draft"]], additivity: "additive", sensitivity: "sensitive", definition: "Total of non-draft invoices issued in the period.", formula: "SUM(invoice total) WHERE issued in period AND not draft/void", sources: ["invoices"] }),
  def("payments_received", { name: "Payments received", module: "analytics_finance", unit: "currency", table: "analytics_fact_payments", agg: "sum", column: "amount", money: true, where: [["direction", "=", "Incoming"]], additivity: "additive", sensitivity: "sensitive", definition: "Incoming payments dated in the period (excluding cancelled or reversed).", formula: "SUM(incoming payment amount)", sources: ["payments"] }),
  def("outstanding_receivables", { name: "Outstanding receivables", module: "analytics_finance", unit: "currency", table: "analytics_fact_invoices", agg: "sum", column: "amountDue", baseColumn: "baseAmountDue", money: true, current: true, where: [["status", "notin", ["Draft", "Paid"]], ["amountDue", ">", 0]], additivity: "semi-additive", sensitivity: "sensitive", definition: "Unpaid balance of issued invoices as of today.", formula: "SUM(amount due) WHERE issued AND unpaid", sources: ["invoices"] }),
  def("overdue_receivables", { name: "Overdue receivables", module: "analytics_finance", unit: "currency", table: "analytics_fact_invoices", agg: "sum", column: "amountDue", baseColumn: "baseAmountDue", money: true, current: true, where: [["status", "notin", ["Draft", "Paid"]], ["amountDue", ">", 0], ["dueDate", "<", "$today"]], additivity: "semi-additive", sensitivity: "sensitive", definition: "Unpaid balance of invoices past their due date as of today.", formula: "SUM(amount due) WHERE dueDate < today", sources: ["invoices"] }),
  def("expenses_amount", { name: "Expenses", module: "analytics_finance", unit: "currency", table: "analytics_fact_expenses", agg: "sum", column: "amount", money: true, where: [["status", "notin", ["Draft", "Rejected", "Cancelled"]]], additivity: "additive", sensitivity: "sensitive", definition: "Submitted or approved expenses dated in the period.", formula: "SUM(expense amount) WHERE not draft/rejected", sources: ["expenses"] }),
  def("budget_planned", { name: "Budget planned", module: "analytics_finance", unit: "currency", table: "analytics_fact_budgets", agg: "sum", column: "planned", snapshot: true, currencyColumn: "currency", additivity: "semi-additive", sensitivity: "sensitive", definition: "Planned amount of active budgets on the last snapshot in the period.", formula: "SUM(active budget lines)", sources: ["budgets"], freshnessTargetMinutes: 1440 }),
  def("budget_actual", { name: "Budget actual", module: "analytics_finance", unit: "currency", table: "analytics_fact_budgets", agg: "sum", column: "actual", snapshot: true, currencyColumn: "currency", additivity: "semi-additive", sensitivity: "sensitive", definition: "Posted journal activity on budgeted accounts for the fiscal year, on the last snapshot in the period.", formula: "SUM(|posted debits − credits|) on budgeted accounts", sources: ["budgets"], freshnessTargetMinutes: 1440 }),

  // AI (usage and governance, not model quality claims)
  def("ai_requests", { name: "AI requests", module: "analytics_ai", unit: "count", table: "analytics_fact_ai_usage", agg: "count", where: [["outcome", "!=", "Shadow"]], additivity: "additive", definition: "AI gateway requests in the period (shadow evaluations excluded).", formula: "COUNT(usage records)", sources: ["ai_usage"] }),
  def("ai_failed_requests", { name: "Failed AI requests", module: "analytics_ai", unit: "count", table: "analytics_fact_ai_usage", agg: "count", where: [["outcome", "in", ["Failed", "Refused"]]], additivity: "additive", definition: "AI requests that failed or were refused in the period.", formula: "COUNT(usage records) WHERE failed/refused", sources: ["ai_usage"] }),
  def("ai_failure_rate", { name: "AI failure rate", module: "analytics_ai", unit: "percent", agg: "ratio", numerator: "ai_failed_requests", denominator: "ai_requests", additivity: "non-additive", definition: "Failed or refused AI requests divided by all AI requests.", formula: "ai_failed_requests / ai_requests", sources: ["ai_usage"] }),
  def("ai_cost", { name: "AI estimated cost", module: "analytics_ai", unit: "usd", table: "analytics_fact_ai_usage", agg: "sum", column: "estimatedCost", fixedCurrency: "USD", additivity: "additive", definition: "Estimated provider cost of AI requests (USD, estimate — not an invoice).", formula: "SUM(estimated cost)", sources: ["ai_usage"] }),
  def("ai_tokens", { name: "AI tokens", module: "analytics_ai", unit: "tokens", table: "analytics_fact_ai_usage", agg: "sum_expr", columns: ["inputTokens", "outputTokens"], additivity: "additive", definition: "Input plus output tokens of AI requests in the period.", formula: "SUM(input + output tokens)", sources: ["ai_usage"] }),
  def("ai_avg_latency_ms", { name: "AI average latency", module: "analytics_ai", unit: "ms", table: "analytics_fact_ai_usage", agg: "avg", column: "durationMs", where: [["outcome", "=", "Succeeded"]], additivity: "non-additive", definition: "Mean duration of successful AI requests.", formula: "AVG(duration ms) WHERE succeeded", sources: ["ai_usage"], nullBehavior: "No value when no request succeeded" }),
  def("ai_proposals", { name: "AI action proposals", module: "analytics_ai", unit: "count", table: "analytics_fact_ai_events", agg: "count", where: [["kind", "=", "proposal"]], additivity: "additive", definition: "Suggested actions proposed by AI in the period.", formula: "COUNT(proposals)", sources: ["ai_events"] }),
  def("ai_proposals_executed", { name: "AI proposals executed", module: "analytics_ai", unit: "count", table: "analytics_fact_ai_events", agg: "count", where: [["kind", "=", "proposal"], ["status", "=", "Executed"]], additivity: "additive", definition: "AI proposals created in the period that a person confirmed and executed.", formula: "COUNT(proposals) WHERE executed", sources: ["ai_events"] }),
  def("ai_safety_events", { name: "AI safety events", module: "analytics_ai", unit: "count", table: "analytics_fact_ai_events", agg: "count", where: [["kind", "=", "safety"]], additivity: "additive", definition: "Safety events recorded in the period (evaluation runs excluded).", formula: "COUNT(safety events)", sources: ["ai_events"] }),
  def("ai_feedback_helpful", { name: "Helpful AI feedback", module: "analytics_ai", unit: "count", table: "analytics_fact_ai_events", agg: "count", where: [["kind", "=", "feedback"], ["status", "=", "Helpful"]], additivity: "additive", definition: "Feedback marked Helpful in the period.", formula: "COUNT(feedback) WHERE Helpful", sources: ["ai_events"] }),
  def("ai_feedback_total", { name: "AI feedback", module: "analytics_ai", unit: "count", table: "analytics_fact_ai_events", agg: "count", where: [["kind", "=", "feedback"]], additivity: "additive", definition: "All AI feedback submitted in the period.", formula: "COUNT(feedback)", sources: ["ai_events"] }),
  def("ai_helpful_rate", { name: "AI helpful rate", module: "analytics_ai", unit: "percent", agg: "ratio", numerator: "ai_feedback_helpful", denominator: "ai_feedback_total", additivity: "non-additive", definition: "Helpful feedback divided by all feedback in the period.", formula: "ai_feedback_helpful / ai_feedback_total", sources: ["ai_events"] }),
];

export const METRIC_BY_KEY = Object.fromEntries(METRICS.map((m) => [m.key, m]));

// Dashboards: which metrics each domain shows and in which order.
export const DASHBOARDS = {
  overview: { module: "analytics_overview", metrics: ["leads_created", "deals_won", "win_rate", "pipeline_value", "activities_completed", "open_tickets", "active_projects", "invoiced_amount", "outstanding_receivables", "ai_requests"] },
  sales: { module: "analytics_sales", metrics: ["leads_created", "leads_qualified", "leads_converted", "lead_conversion_rate", "deals_created", "deals_won", "deals_lost", "win_rate", "pipeline_value", "weighted_pipeline", "open_deals", "deals_without_next_action", "quotes_value", "quotes_accepted", "orders_value", "renewal_exposure"], trend: "leads_created", breakdown: { metric: "pipeline_value", dimension: "stage" } },
  activities: { module: "analytics_activities", metrics: ["activities_created", "activities_completed", "activities_overdue", "activity_completion_rate"], trend: "activities_completed", breakdown: { metric: "activities_created", dimension: "type" } },
  support: { module: "analytics_support", metrics: ["tickets_created", "tickets_resolved", "open_tickets", "avg_first_response_minutes", "avg_resolution_minutes", "sla_response_breach_rate", "reopened_tickets"], trend: "tickets_created", breakdown: { metric: "tickets_created", dimension: "priority" } },
  projects: { module: "analytics_projects", metrics: ["active_projects", "projects_at_risk", "tasks_completed", "tasks_overdue", "hours_logged", "billable_hours", "billable_ratio"], trend: "hours_logged", breakdown: { metric: "active_projects", dimension: "health" } },
  finance: { module: "analytics_finance", metrics: ["invoiced_amount", "payments_received", "outstanding_receivables", "overdue_receivables", "expenses_amount", "budget_planned", "budget_actual"], trend: "invoiced_amount", breakdown: { metric: "invoiced_amount", dimension: "status" } },
  ai: { module: "analytics_ai", metrics: ["ai_requests", "ai_failure_rate", "ai_cost", "ai_tokens", "ai_avg_latency_ms", "ai_proposals", "ai_proposals_executed", "ai_safety_events", "ai_helpful_rate"], trend: "ai_requests", breakdown: { metric: "ai_requests", dimension: "capability" } },
};

// Metric keys that depend on a warehouse source (for data-quality staleness).
export function metricKeysForSource(source) {
  const direct = METRICS.filter((m) => (m.sources || []).includes(source)).map((m) => m.key);
  return [...new Set(direct)];
}

// The serializable definition stored in a registry version.
export function definitionPayload(m) {
  const t = m.table ? TABLES[m.table] : null;
  return {
    definition: m.definition, formula: m.formula, implementation: m.agg === "ratio" ? `ratio(${m.numerator}, ${m.denominator})` : `${m.agg}(${m.table}${m.column ? `.${m.column}` : ""})`,
    sources: m.sources, sourceFields: [m.column, ...(m.columns || [])].filter(Boolean), filters: m.where || [], grain: m.snapshot ? "snapshot day" : m.current ? "as of now" : "business day",
    dimensions: t ? Object.keys(t.dims) : [], currencyBehavior: m.money ? "Per original currency, plus base currency at the rate on the business date" : m.fixedCurrency ? `Fixed ${m.fixedCurrency}` : m.currencyColumn ? "Budget currency" : "Not monetary",
    additivity: m.additivity, type: m.agg, nullBehavior: m.nullBehavior, owner: "Analytics", reviewer: "Finance and operations leads",
    permissions: [m.module], sensitivity: m.sensitivity, dataQuality: "Reconciled against source counts and totals after each load", freshnessTargetMinutes: m.freshnessTargetMinutes, unit: m.unit,
    dateColumn: m.dateColumn || (t ? t.date : null),
  };
}

// Dimensions a metric can be grouped or filtered by (ratios: those both parts support).
export function metricDimensions(key) {
  const m = METRIC_BY_KEY[key];
  if (!m) return [];
  if (m.agg === "ratio") { const a = metricDimensions(m.numerator); const b = new Set(metricDimensions(m.denominator)); return a.filter((d) => b.has(d)); }
  return Object.keys(TABLES[m.table].dims);
}
