// Print-ready PDF export for the AI Intelligence Overview — same jsPDF +
// jspdf-autotable pattern already used by Invoice/Contract/Quote/Order
// detail pages, not a new dependency or a new export mechanism.
//
// The disclosure that this is a Frontend Analysis Preview, not a real AI
// provider, is baked into the document itself (header and footer of every
// page) — once downloaded, a PDF can be viewed or printed completely out of
// the app's context, so the page's own on-screen badge isn't enough.
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

const MARGIN = 14;
const PAGE_WIDTH = 210; // A4 portrait, mm

function addDisclosureFooter(doc) {
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(7.5);
    doc.setTextColor(140);
    doc.text(
      "Frontend Analysis Preview — calculated from frontend fixture data. Not generated by Claude, OpenAI or any external AI provider. Every recommendation requires human review.",
      MARGIN, 289, { maxWidth: PAGE_WIDTH - MARGIN * 2 }
    );
    doc.text(`Page ${i} of ${pageCount}`, PAGE_WIDTH - MARGIN, 289, { align: "right" });
  }
  doc.setTextColor(0);
}

/**
 * Builds (but does not save) the jsPDF document for the current analysis.
 * Kept separate from downloadOverviewPdf so the construction logic — the
 * part worth testing — never has to trigger a real browser download.
 */
export function buildOverviewPdfDocument({ response, metrics, insights, viewLabel, role }) {
  const doc = new jsPDF();

  doc.setFontSize(16);
  doc.text("AI Intelligence Overview", MARGIN, 18);
  doc.setFontSize(9);
  doc.setTextColor(120);
  doc.text("Frontend Analysis Preview — not connected to a real AI provider", MARGIN, 24);
  doc.setTextColor(0);

  doc.setFontSize(9);
  doc.text(`Scope: ${viewLabel}   ·   Role: ${role}`, MARGIN, 32);
  doc.text(`Generated: ${new Date(response.dataDate.generatedAt).toLocaleString()}   ·   ${response.dataDate.recordCount} records considered`, MARGIN, 37.5);

  doc.setFontSize(11);
  doc.text("Executive Summary", MARGIN, 47);
  doc.setFontSize(9);
  const summaryLines = doc.splitTextToSize(response.executiveSummary, PAGE_WIDTH - MARGIN * 2);
  doc.text(summaryLines, MARGIN, 53);
  let y = 53 + summaryLines.length * 4.5 + 6;

  if (metrics) {
    autoTable(doc, {
      startY: y,
      head: [["Critical Risks", "Opportunities", "Suggested Actions", "Records Needing Attention", "Data Quality Issues", "High Confidence"]],
      body: [[
        metrics.criticalRisks, metrics.opportunities, metrics.suggestedActions, metrics.recordsNeedingAttention,
        metrics.dataQualityIssues, metrics.highConfidenceShare !== null ? `${metrics.highConfidenceShare}%` : "—",
      ]],
      styles: { fontSize: 8, halign: "center" },
      headStyles: { fillColor: [30, 41, 59] },
      margin: { left: MARGIN, right: MARGIN },
    });
    y = doc.lastAutoTable.finalY + 8;
  }

  if (insights.length === 0) {
    doc.setFontSize(9);
    doc.text("No insights match the current filters.", MARGIN, y);
    y += 8;
  } else {
    autoTable(doc, {
      startY: y,
      head: [["Priority", "Module", "Insight", "Confidence", "Records"]],
      body: insights.map((i) => [i.priority, i.module, `${i.title}\n${i.summary}`, i.confidence.level, String(i.affectedRecordIds.length)]),
      styles: { fontSize: 7.5, cellPadding: 2, valign: "top" },
      headStyles: { fillColor: [30, 41, 59] },
      columnStyles: { 2: { cellWidth: 90 } },
      margin: { left: MARGIN, right: MARGIN },
    });
    y = doc.lastAutoTable.finalY + 8;
  }

  if (y > 260) { doc.addPage(); y = 20; }
  doc.setFontSize(11);
  doc.text("Analysis Limitations", MARGIN, y);
  doc.setFontSize(8.5);
  y += 6;
  for (const limitation of response.limitations) {
    const lines = doc.splitTextToSize(`•  ${limitation}`, PAGE_WIDTH - MARGIN * 2);
    if (y + lines.length * 4 > 275) { doc.addPage(); y = 20; }
    doc.text(lines, MARGIN, y);
    y += lines.length * 4 + 2;
  }

  addDisclosureFooter(doc);
  return doc;
}

export function downloadOverviewPdf(args) {
  const doc = buildOverviewPdfDocument(args);
  doc.save(`ai-intelligence-overview-${new Date().toISOString().slice(0, 10)}.pdf`);
}
