// Backend Phase 9 — generation endpoints (AI Overview narrative and explore,
// suggest-an-action), request status, live events, cancellation, feedback.
import crypto from "node:crypto";
import prisma from "../../lib/prisma.js";
import { hasGrant } from "../../utils/grants.js";
import { guard, notFound, invalid } from "./common.js";
import { AiError, CATEGORIES } from "../common/errors.js";
import { aiAudit } from "../common/audit.js";
import { runAi, cancelAiRequest, aiEvents, isTerminal } from "../gateway/gateway.js";
import { narrativeRequestSchema, exploreRequestSchema } from "../../services/ai/schemas.js";
import { loadTarget } from "../actions/actionTypes.js";
import { previewAction, serializeProposal } from "../actions/actionService.js";
import { ACTION_TYPES } from "../actions/actionTypes.js";

const firstIssue = (parsed) => parsed.error.issues[0]?.message || "Invalid request";
const canSeeRequest = (req, r) => r.membershipId === req.membership?.id || hasGrant(req, "ai_audit", "view");

// The deterministic summary is what users see whenever the AI text can't be
// verified (refused, invented numbers, claimed actions, empty).
function narrativeFrom(executiveSummary, outcome) {
  const text = outcome?.output?.text;
  const clean = !!text && !outcome.refused && !(outcome.validation?.warnings || []).length;
  return { narrative: clean ? text : executiveSummary, numbersVerified: clean, usedDeterministicFallback: !clean };
}

export const narrative = guard(async (req, res) => {
  const parsed = narrativeRequestSchema.safeParse(req.body);
  if (!parsed.success) throw invalid(firstIssue(parsed));
  const { provider, executiveSummary, facts } = parsed.data;
  const base = {
    req, useCaseKey: "overview.narrative", providerKey: provider || undefined, idempotencyKey: req.get("Idempotency-Key") || undefined,
    dataVariables: { executiveSummary, facts }, numericFacts: facts,
  };
  if (req.body.stream === true) {
    const request = await prisma.aiRequest.create({ data: { organizationId: req.organizationId, userId: req.user?.id || null, membershipId: req.membership?.id || null, useCaseKey: "overview.narrative", correlationId: crypto.randomUUID(), status: "Queued" } });
    setImmediate(() => {
      runAi({ ...base, stream: true, requestId: request.id, idempotencyKey: undefined, finalize: (output, validation, refused) => narrativeFrom(executiveSummary, { output, validation, refused }) }).catch(() => {});
    });
    return res.status(202).json({ requestId: request.id, eventsUrl: `/api/v1/ai/requests/${request.id}/events`, note: "Streamed text is a draft; the validated result replaces it." });
  }
  const outcome = await runAi(base);
  res.json({ ...narrativeFrom(executiveSummary, outcome), provider: outcome.provider, requestId: outcome.request.id, generatedAt: new Date().toISOString() });
});

function knownIds(records) {
  const ids = new Set();
  for (const list of Object.values(records || {})) if (Array.isArray(list)) for (const r of list) if (r?._id) ids.add(String(r._id));
  return ids;
}

export const explore = guard(async (req, res) => {
  const parsed = exploreRequestSchema.safeParse(req.body);
  if (!parsed.success) throw invalid(firstIssue(parsed));
  const { provider, question, scopeLabel, records } = parsed.data;
  const outcome = await runAi({
    req, useCaseKey: "overview.explore", providerKey: provider || undefined, idempotencyKey: req.get("Idempotency-Key") || undefined,
    dataVariables: { records },
    textVariables: { role: req.membership?.roles?.[0]?.name || req.user?.role || "User", scopeLabel, questionLine: question ? `The user specifically asked: "${question}"` : "The user asked for a general review of this data." },
  });
  if (outcome.refused) throw new AiError(CATEGORIES.CONTENT_REFUSED, "The AI model declined to analyze these records.");
  // The model's JSON is untrusted: citations and suggestions must resolve
  // against records that were actually sent.
  const ids = knownIds(records);
  const findings = (outcome.output.findings || []).map((f) => ({
    ...f, citedRecordIds: f.citedRecordIds.filter((id) => ids.has(id)),
    suggestedAction: f.suggestedAction && ids.has(f.suggestedAction.affectedRecordId) ? f.suggestedAction : undefined,
  }));
  res.json({
    findings, truncated: !!outcome.truncated, provider: outcome.provider, requestId: outcome.request.id, generatedAt: new Date().toISOString(),
    disclaimer: `Generated by ${outcome.provider.label} (${outcome.provider.model}) over your current records.${outcome.provider.simulatorLabel ? ` ${outcome.provider.simulatorLabel}` : ""} Not verified by the deterministic engine — figures and conclusions may be wrong. Always confirm before acting.`,
  });
});

// Asks the model for one governed action on a record → a preview only.
export const suggestAction = guard(async (req, res) => {
  const { targetType, targetId, goal } = req.body || {};
  if (!targetType || !targetId) throw invalid("targetType and targetId are required.");
  const target = await loadTarget(req, targetType, String(targetId));
  const outcome = await runAi({ req, useCaseKey: "action.proposal", dataVariables: { record: target.record }, textVariables: { recordType: targetType, goal: String(goal || "Suggest the most useful next step").slice(0, 300) } });
  if (outcome.refused) throw new AiError(CATEGORIES.CONTENT_REFUSED, "The AI model declined to suggest an action.");
  const s = outcome.output;
  if (!ACTION_TYPES[s.actionType]?.targets.includes(targetType)) throw new AiError(CATEGORIES.CONTENT_REFUSED, "The AI suggestion doesn't apply to this record, so it was discarded.");
  const evidence = (s.supportingFields || []).filter((f) => f in (target.record || {})).map((f) => ({ recordType: targetType, recordId: String(targetId), field: f, value: target.record[f] ?? null }));
  const proposal = await previewAction(req, { actionType: s.actionType, targetType, targetId, proposedValues: s.proposedValues, reason: s.reason, evidence, source: "Model", requestId: outcome.request.id });
  res.status(201).json({ proposal: serializeProposal(proposal, req), provider: outcome.provider, note: "This is a proposal. Nothing changes until you confirm it." });
});

export const getRequest = guard(async (req, res) => {
  const r = await prisma.aiRequest.findFirst({ where: { id: req.params.id, organizationId: req.organizationId } });
  if (!r || !canSeeRequest(req, r)) return notFound(res, "AI request");
  res.json({
    request: {
      _id: r.id, useCaseKey: r.useCaseKey, status: r.status, providerKey: r.providerKey, modelId: r.modelId, alias: r.alias, mode: r.mode,
      errorCategory: r.errorCategory, safeError: r.safeError, removedFields: r.removedFields, injectionFlags: r.injectionFlags, validation: r.validation,
      result: isTerminal(r.status) ? r.result : null, inputChars: r.inputChars, outputChars: r.outputChars, attempts: r.attempts,
      startedAt: r.startedAt, completedAt: r.completedAt, durationMs: r.durationMs, createdAt: r.createdAt,
    },
  });
});

// Server-sent events: persisted progress (replayed), live drafts, and a
// final event. Draft text is never the final answer.
export async function requestEvents(req, res) {
  const r = await prisma.aiRequest.findFirst({ where: { id: req.params.id, organizationId: req.organizationId } });
  if (!r || !canSeeRequest(req, r)) return res.status(404).json({ code: "AI_NOT_FOUND", message: "AI request not found." });
  res.writeHead(200, { "Content-Type": "text/event-stream", "Cache-Control": "no-cache, no-transform", Connection: "keep-alive", "X-Accel-Buffering": "no" });
  const send = (e) => res.write(`event: ${e.type}\ndata: ${JSON.stringify({ seq: e.seq ?? null, ...e.data, draft: e.type === "draft" || undefined })}\n\n`);
  let lastSeq = 0;
  const past = await prisma.aiRequestEvent.findMany({ where: { requestId: r.id }, orderBy: { seq: "asc" } });
  for (const e of past) { send(e); lastSeq = e.seq; }
  const end = () => { clearInterval(ping); aiEvents.off(r.id, onEvent); res.end(); };
  const onEvent = (e) => {
    if (e.seq && e.seq <= lastSeq) return;
    if (e.seq) lastSeq = e.seq;
    send(e);
    if (["completed", "failed", "cancelled"].includes(e.type)) end();
  };
  const ping = setInterval(() => res.write(": ping\n\n"), 15_000);
  const fresh = await prisma.aiRequest.findUnique({ where: { id: r.id } });
  if (isTerminal(fresh.status)) { if (!past.some((e) => ["completed", "failed", "cancelled"].includes(e.type))) send({ type: "completed", data: { status: fresh.status } }); return end(); }
  aiEvents.on(r.id, onEvent);
  req.on("close", () => { clearInterval(ping); aiEvents.off(r.id, onEvent); });
}

export const cancelRequest = guard(async (req, res) => {
  const r = await prisma.aiRequest.findFirst({ where: { id: req.params.id, organizationId: req.organizationId } });
  if (!r || (r.membershipId !== req.membership?.id && !hasGrant(req, "ai_providers", "configure"))) return notFound(res, "AI request");
  const updated = await cancelAiRequest(req.organizationId, r.id);
  await aiAudit(req, "ai.request.cancelled", "AiRequest", r.id);
  res.json({ request: { _id: updated.id, status: updated.status }, note: "Usage already incurred at the provider is still recorded." });
});

const RATINGS = ["Helpful", "Not Helpful", "Incorrect", "Unsafe", "Missing evidence"];
export const feedback = guard(async (req, res) => {
  const { requestId = null, proposalId = null, rating, reason = null, comment = null } = req.body || {};
  if (!RATINGS.includes(rating)) throw invalid(`rating: ${RATINGS.join(", ")}.`);
  if (!requestId && !proposalId) throw invalid("requestId or proposalId is required.");
  if (requestId && !(await prisma.aiRequest.findFirst({ where: { id: requestId, organizationId: req.organizationId } }))) return notFound(res, "AI request");
  if (proposalId && !(await prisma.aiActionProposal.findFirst({ where: { publicId: proposalId, organizationId: req.organizationId } }))) return notFound(res, "Action proposal");
  const row = await prisma.aiFeedback.create({ data: { organizationId: req.organizationId, membershipId: req.membership?.id || null, requestId, proposalId, rating, reason: reason ? String(reason).slice(0, 200) : null, comment: comment ? String(comment).slice(0, 2000) : null } });
  if (rating === "Unsafe") await aiAudit(req, "ai.feedback.unsafe", "AiFeedback", row.id, { after: { requestId, proposalId } });
  res.status(201).json({ feedback: { _id: row.id, rating: row.rating }, note: "Feedback is used for evaluations by authorized reviewers. It never retrains a model." });
});
