// CRM page guides. Plain language for everyday staff; tour targets are
// data-tour="…" attributes on the pages.
const crm = [
  {
    path: "/crm/leads",
    title: "Leads",
    purpose: "A lead is a person or company who might become a customer but hasn't been confirmed yet. Use this page to keep every new enquiry in one list, follow up on time, and turn good leads into customers.",
    sections: [
      { heading: "Summary cards", body: "The six cards count the leads you can see: all of them, new ones, qualified ones, follow-ups due, overdue follow-ups, and the share converted into customers. Click a card to show only those leads." },
      { heading: "Search and filters", body: "Search by name, company, email or phone. Narrow the list by status, source, priority, owner or department. Tick Archived to see leads that were put away." },
      { heading: "Columns and views", body: "Columns chooses which details the table shows. Views saves your current search and filters under a name, so you can reopen the same list later with one click." },
      { heading: "Working on several leads at once", body: "Tick the boxes on the left of the table to select leads. You can then assign them to someone, change their status or archive them together. Every change asks for a short reason, which is kept in the history." },
      { heading: "Import and export", body: "Import brings in leads from a spreadsheet file. Export downloads the leads you currently see, with your filters applied." },
    ],
    tips: [
      "Open a lead by clicking its name.",
      "The Overdue card turns red when a promised follow-up date has passed. Check it every morning.",
    ],
    tour: [
      { target: "leads-add", title: "Add a lead", body: "Create a new lead here: a name and a way to reach them is enough to start. You can add details later." },
      { target: "leads-summary", title: "Your leads at a glance", body: "These cards count your leads. Click one, for example Overdue, to show only those leads in the table." },
      { target: "leads-filters", title: "Find the right leads", body: "Search by name, company, email or phone, and use the drop-downs to filter by status, source, priority, owner or department." },
      { target: "leads-views", title: "Save a view", body: "Set up the filters you use often, then save them here as a view to reopen the same list with one click." },
      { target: "leads-table", title: "The lead list", body: "Click a lead's name to open it. Tick the boxes on the left to assign, re-status or archive several leads at once." },
      { target: "leads-actions", title: "Import and export", body: "Bring leads in from a spreadsheet with Import, or download the current list with Export." },
    ],
  },
  {
    path: "/crm/leads/:id",
    title: "Lead",
    purpose: "Everything about one lead: who they are, how far they have come, and what has been done so far. From here you move the lead forward until it becomes a customer, or close it.",
    sections: [
      { heading: "Progress", body: "A lead moves through New → Attempted → Contacted → Qualified → Converted. The highlighted steps show where this lead is. \"Move to …\" takes it to the next step." },
      { heading: "Convert", body: "When a lead is Qualified, Convert turns it into a customer. It creates the company, the contact and a deal in one go, and opens the new company." },
      { heading: "Disqualify and archive", body: "Disqualify closes a lead that won't become a customer, with the reason why. Archive removes a lead from the everyday list without deleting it; an administrator can restore it." },
      { heading: "Tabs", body: "Overview shows the lead's details and lets you add a note. Activity is the history of calls, emails and changes. Tasks lists follow-ups and shows overdue ones in red. Files holds attachments. Administrators also see Audit, the full change log." },
      { heading: "Notes, activities and follow-ups", body: "Add a note for anything worth remembering. Log Activity records a call, email or meeting that happened. Schedule Follow-up sets the next date you'll get back to them." },
    ],
    tips: ["Always schedule the next follow-up before you leave a lead, so it can't be forgotten."],
    tour: [
      { target: "lead-workflow", title: "Where this lead is", body: "The steps from New to Converted. The highlighted ones show how far this lead has come." },
      { target: "lead-actions", title: "Move the lead forward", body: "Edit the details, give the lead to a colleague with Assign, move it to the next step, convert it into a customer once it is Qualified, or disqualify or archive it." },
      { target: "lead-tabs", title: "Details, history and tasks", body: "Switch between the lead's overview, its activity history, its tasks and follow-ups, and its files." },
      { target: "lead-log", title: "Record what happened", body: "Log a call, email or meeting, and schedule the next follow-up so it appears in your tasks." },
    ],
  },
  {
    path: "/crm/dashboard",
    title: "CRM Dashboard",
    purpose: "Your daily starting point: new leads, the value of open deals, what was won, and which activities and deals need attention. Every figure is a link to the records behind it.",
    sections: [
      { heading: "Views", body: "My Dashboard shows your own work. Team Dashboard shows your team's pipeline and activities. Management Overview compares the whole business, including won and lost deals and each team's results." },
      { heading: "Period and filters", body: "Choose the time period at the top. The filters below narrow every figure on the page, for example to one owner or one team." },
      { heading: "Key figures", body: "The cards across the top: new leads, how many leads became customers, the value of open deals, the weighted value (each deal's value multiplied by its chance of winning), deals won, and overdue activities. Click a card to open the matching list." },
      { heading: "Activities and at-risk deals", body: "What's due today and overdue, and the deals that need attention before they slip." },
      { heading: "Customize", body: "Choose which extra sections appear (lead sources, forecast, companies needing attention, recent activity, team performance) and in what order." },
    ],
    tips: ["Weighted value is the realistic forecast: a 100,000 deal at the Proposal stage (50%) counts as 50,000."],
    tour: [
      { target: "dash-views", title: "Choose a view", body: "Switch between your own figures, your team's, and the management overview." },
      { target: "dash-range", title: "Pick the period", body: "Every figure on the page follows the period you choose here." },
      { target: "dash-kpis", title: "The key figures", body: "New leads, conversion, open and weighted pipeline, deals won and overdue activities. Click any card to see the records behind it." },
      { target: "dash-activities", title: "What needs doing", body: "Activities due today and overdue, so nothing slips through." },
      { target: "dash-customize", title: "Make it yours", body: "Show, hide and reorder the extra sections of the dashboard." },
      { target: "dash-create", title: "Create something quickly", body: "Add a lead, contact, company, deal or activity from here without leaving the dashboard." },
    ],
  },
  {
    path: "/crm/companies",
    title: "Companies",
    purpose: "The organisations you deal with: prospects, customers, partners and vendors. Each company brings together its people, deals, support tickets, projects and invoices.",
    sections: [
      { heading: "Summary cards", body: "Counts of all companies, prospects, active customers, companies at risk, follow-ups due and companies nobody owns yet. Click a card to show just those." },
      { heading: "Types, stages and health", body: "Type says what the company is to you: Prospect, Customer, Partner, Vendor or Former Customer. Lifecycle stage says where the relationship is, from New and Onboarding to Active, Renewal Due or Churned. Health (Healthy, Needs Attention, At Risk, Inactive) is how the relationship is going." },
      { heading: "Search, filters and views", body: "Search by name, web address, email or phone, and filter by type, stage, tier, health, owner or team. Save filters you use often as a view." },
      { heading: "Several companies at once", body: "Tick companies in the table to assign an owner, add a tag, change the lifecycle stage, archive them, or export just those." },
    ],
    tips: ["Check the At-Risk card regularly: those customers need a call before they leave."],
    tour: [
      { target: "companies-add", title: "Add a company", body: "Create a company record. Contacts and deals can be linked to it afterwards." },
      { target: "companies-summary", title: "Your companies at a glance", body: "Click a card, for example At-Risk or Unassigned, to show only those companies." },
      { target: "companies-filters", title: "Find companies", body: "Search, and filter by type, lifecycle stage, tier, health, owner or team." },
      { target: "companies-views", title: "Save a view", body: "Keep a filter combination you use often and reopen it with one click." },
      { target: "companies-table", title: "The company list", body: "Click a name to open the company. Tick rows to change several companies at once." },
    ],
  },
  {
    path: "/crm/companies/:id",
    title: "Company",
    purpose: "Everything about one organisation on one page: its details, its people, and all the work with it across sales, support, projects and finance.",
    sections: [
      { heading: "Badges", body: "Under the name: the company's type, lifecycle stage, tier and health. Hover over the health badge to see why it was set." },
      { heading: "Actions", body: "Edit the details, add a contact, add a note, log a call or meeting, create a task or schedule a meeting. The \"…\" menu changes the owner, lifecycle stage or health, or archives the company." },
      { heading: "Tabs", body: "Overview holds the company details. Contacts lists its people and which one is the main contact. Activity is the history. Deals, Support, Projects and Finance show that company's opportunities, tickets, projects and invoices. Tasks, Files and Audit (the change log) complete the picture." },
    ],
    tips: ["Mark one contact as primary so everyone knows who to call first."],
    tour: [
      { target: "company-badges", title: "The company in four badges", body: "Type, lifecycle stage, tier and health: a quick read of the relationship." },
      { target: "company-actions", title: "Everyday actions", body: "Add a contact or note, log what happened, create a task, or schedule a meeting." },
      { target: "company-more", title: "More actions", body: "Change the owner, lifecycle stage or health, or archive the company." },
      { target: "company-tabs", title: "All the work in one place", body: "Contacts, activity, deals, support tickets, projects, invoices, tasks and files for this company." },
    ],
  },
  {
    path: "/crm/contacts",
    title: "Contacts",
    purpose: "The people you deal with, usually at a company. Use this page to find someone quickly, keep follow-ups on time and respect who doesn't want to be contacted.",
    sections: [
      { heading: "Summary cards", body: "Counts of all contacts, prospects, active customers, follow-ups due, overdue follow-ups and people marked Do Not Contact. Click a card to show just those." },
      { heading: "Relationship and stage", body: "Relationship says who the person is to you: Customer, Prospect, Former Customer, Partner or Vendor. Lifecycle stage (New, Engaged, Active, At Risk, Churned) says how the relationship is going." },
      { heading: "Search, filters and views", body: "Search and filter the list, and save combinations you use often as a view." },
      { heading: "Do Not Contact", body: "Some people have asked not to be contacted. Their records are marked, and the system warns you before you schedule anything with them." },
    ],
    tour: [
      { target: "contacts-add", title: "Add a contact", body: "Create a person's record and link them to their company." },
      { target: "contacts-summary", title: "Your contacts at a glance", body: "Click a card, for example Overdue, to show only those people." },
      { target: "contacts-filters", title: "Find people", body: "Search by name or details and narrow the list with the filters." },
      { target: "contacts-views", title: "Save a view", body: "Keep a filter combination and reopen it later with one click." },
      { target: "contacts-table", title: "The contact list", body: "Click a name to open the contact. Tick rows to change several at once." },
    ],
  },
  {
    path: "/crm/contacts/:id",
    title: "Contact",
    purpose: "One person: how to reach them, their company, and every call, email, meeting, deal and ticket involving them.",
    sections: [
      { heading: "Badges", body: "Relationship, lifecycle stage and communication status. Communication status is Active, Restricted, or Do Not Contact." },
      { heading: "Actions", body: "Edit, add a note, log an activity, create a task or schedule a meeting. The \"…\" menu changes the owner or lifecycle stage, marks the person Do Not Contact (or removes it), or archives them." },
      { heading: "Tabs", body: "Overview, Activity, Deals, Support, Projects, Finance, Tasks, Files and Audit: everything connected to this person." },
    ],
    tips: ["If someone asks not to be contacted, use \"Mark Do Not Contact\" straight away. It protects the company and the customer."],
    tour: [
      { target: "contact-badges", title: "Who this person is to you", body: "Relationship, lifecycle stage and whether you may contact them." },
      { target: "contact-actions", title: "Record your work", body: "Add notes, log calls and meetings, create tasks and schedule meetings." },
      { target: "contact-more", title: "More actions", body: "Change the owner or stage, set Do Not Contact, or archive the contact." },
      { target: "contact-tabs", title: "Everything about them", body: "Their activity, deals, tickets, projects, invoices, tasks and files." },
    ],
  },
  {
    path: "/crm/deals",
    title: "Deals",
    purpose: "Every sales opportunity in a list: what it's worth, which stage it's at, and when it's expected to close. Use it to keep the pipeline accurate and to act on deals that are slipping.",
    sections: [
      { heading: "Summary cards", body: "Open pipeline (the total value of open deals), weighted pipeline (each deal's value multiplied by its chance of winning), deals closing this month, deals at risk, and deals won and lost in this period. Click a card to show just those." },
      { heading: "Stages", body: "Deals move through Discovery (10%), Qualified (25%), Proposal (50%), Negotiation (70%) and Approval (90%) to Won. The percentage is the usual chance of winning at that stage." },
      { heading: "Several deals at once", body: "Tick deals to assign an owner, change the stage, add a tag or archive them together." },
      { heading: "Pipeline", body: "The Pipeline button shows the same deals as a board, with one column per stage." },
    ],
    tour: [
      { target: "deals-add", title: "Add a deal", body: "Record a new opportunity with its value, expected close date and stage." },
      { target: "deals-summary", title: "The pipeline in numbers", body: "Open and weighted value, deals closing soon, at-risk deals, and what was won or lost. Click a card to filter." },
      { target: "deals-filters", title: "Find deals", body: "Search and filter the list, for example to your own open deals." },
      { target: "deals-table", title: "The deal list", body: "Click a deal to open it. Tick rows to change several at once." },
      { target: "deals-pipeline", title: "See it as a board", body: "Open the pipeline board to move deals between stages by dragging." },
    ],
  },
  {
    path: "/crm/deals/:id",
    title: "Deal",
    purpose: "One sales opportunity: its value, stage, people, products and quotes, and everything done so far. From here you move it forward and record whether it was won or lost.",
    sections: [
      { heading: "Stage bar", body: "Shows the stages and where this deal is. Click a stage to move the deal there; you'll be asked to confirm, and the move is recorded in Stage History." },
      { heading: "Actions", body: "Edit, log an activity, schedule a follow-up, and record the outcome: Mark Won, Mark Lost (with the reason) or put it On Hold. A closed deal can be reopened, and any deal can be archived." },
      { heading: "Tabs", body: "Overview, Activities, Contacts involved, Products (what's being sold), Quotes, Stage History, Tasks, Files and Audit." },
    ],
    tips: ["Always give the reason when you mark a deal lost. The reasons show why deals are lost and help win the next ones."],
    tour: [
      { target: "deal-stages", title: "Where the deal is", body: "Click a stage to move the deal forward. Each move is recorded." },
      { target: "deal-actions", title: "Work on the deal", body: "Edit it, log what happened, and schedule the next follow-up." },
      { target: "deal-outcome", title: "Record the outcome", body: "Mark the deal won, lost (with the reason) or on hold." },
      { target: "deal-tabs", title: "Details and history", body: "Contacts, products, quotes, stage history, tasks and files for this deal." },
    ],
  },
  {
    path: "/crm/pipeline",
    title: "Sales Pipeline",
    purpose: "Your open deals as a board, with one column per stage. It's the quickest way to see what's moving and what's stuck, and to move deals forward.",
    sections: [
      { heading: "Pipelines", body: "Choose the pipeline: New Business for new customers, Renewals for existing contracts, Partnerships for partner deals." },
      { heading: "Summary cards", body: "Open and weighted value, deals closing this month, at-risk deals, stale deals (no recent activity) and the average deal size." },
      { heading: "Moving deals", body: "Drag a card to another column to change its stage. Or use the card's \"⋮\" menu, which also works on touch screens and with the keyboard. Click a card to preview the deal." },
      { heading: "Filters, sorting and grouping", body: "Search, filter by owner, team, health or priority, and choose how cards are sorted and grouped." },
      { heading: "Board Settings", body: "Choose what the board shows, such as column totals and weighted values." },
    ],
    tour: [
      { target: "pipeline-selector", title: "Choose the pipeline", body: "New Business, Renewals or Partnerships. Each has its own deals." },
      { target: "pipeline-summary", title: "The numbers", body: "Open and weighted value, deals closing soon, at-risk and stale deals, and the average deal size." },
      { target: "pipeline-filters", title: "Focus the board", body: "Search, filter, sort and group the cards." },
      { target: "pipeline-board", title: "Move deals", body: "Drag a card to the next stage, or use its \"⋮\" menu. Click a card to preview it." },
      { target: "pipeline-settings", title: "Board settings", body: "Choose what the columns show." },
      { target: "pipeline-add", title: "Add a deal", body: "Create a new deal straight onto the board." },
    ],
  },
  {
    path: "/crm/activities",
    title: "Activities",
    purpose: "All your calls, emails, meetings, follow-ups, tasks, notes and customer visits in one place, so you always know what's due and what was done.",
    sections: [
      { heading: "Summary cards", body: "Due today, overdue, upcoming, completed in the last 7 days, and activities nobody is assigned to. Click a card to show just those." },
      { heading: "Three ways to look", body: "Agenda lists what's coming up day by day. Table shows everything with filters and sorting. Calendar shows the week or month." },
      { heading: "Filters and views", body: "Filter by type, status, owner and more, and save a combination as a view." },
    ],
    tips: ["Start the day with the Overdue card, then Due Today."],
    tour: [
      { target: "activities-add", title: "Create an activity", body: "Plan a call, meeting, email, follow-up, task or visit, and link it to a lead, contact, company or deal." },
      { target: "activities-summary", title: "What's due", body: "Due today, overdue, upcoming and recently completed. Click a card to filter." },
      { target: "activities-views", title: "Agenda, table or calendar", body: "Switch between the day-by-day agenda, a full table and a calendar." },
      { target: "activities-filters", title: "Narrow it down", body: "Filter by type, status or owner, and save the filters as a view." },
    ],
  },
  {
    path: "/crm/import",
    title: "Import CRM Records",
    purpose: "Bring leads, contacts, companies or deals in from a spreadsheet (CSV or Excel), checking each row before it is saved.",
    sections: [
      { heading: "The steps", body: "1. Record type: what you're importing. 2. Upload: choose the file (up to 5 MB). 3. Mapping: match your spreadsheet's columns to CRM fields; common names are matched for you. 4. Validation: rows with missing or wrong values are shown so you can fix or skip them. 5. Duplicates: rows that match existing records. For each, choose to skip it, create it as a new record, update the existing record with it, or review it manually (it is left out of this import). 6. Review: a final summary. 7. Results: what was created, updated or skipped." },
      { heading: "Your file", body: "The file is read in your browser; each accepted row is then saved like a record you entered by hand, with the same checks and history." },
    ],
    tips: ["Try a small file of 10 to 20 rows first to check the mapping, then import the rest."],
    tour: [
      { target: "import-steps", title: "Seven steps", body: "You can go back to any step you've already completed." },
      { target: "import-panel", title: "The current step", body: "Follow the instructions here. Nothing is saved until you confirm on the Review step." },
    ],
  },
  {
    path: "/crm/duplicates",
    title: "Duplicate Management",
    purpose: "Find records that probably describe the same person, company or deal, compare them side by side, and decide which ones really are duplicates.",
    sections: [
      { heading: "Summary cards", body: "Duplicate groups found, high-confidence matches, groups waiting for review, confirmed duplicates, groups marked not duplicate, and groups resolved in preview." },
      { heading: "Reviewing a group", body: "Open a group to compare the records field by field. You can confirm the records are duplicates, mark them not duplicate, defer the decision, or assign the group to someone else. Merges are always reviewed one group at a time." },
      { heading: "Merge History", body: "The merges done on this page, which can be undone." },
      { heading: "Important", body: "Merging on this page is currently a preview: it shows the result but doesn't change your saved records yet." },
    ],
    tour: [
      { target: "duplicates-summary", title: "What was found", body: "How many possible duplicates there are, and how far the review has got." },
      { target: "duplicates-filters", title: "Choose what to review", body: "Filter by record type, confidence and review status." },
      { target: "duplicates-table", title: "Duplicate groups", body: "Open a group to compare its records side by side and decide." },
      { target: "duplicates-history", title: "Merge History", body: "Merges done here, which can be undone." },
    ],
  },
];

export default crm;
