// Marketing page guides. Marketing still runs on sample data (see the
// DemoNotice in MarketingLayout), so every guide says so plainly.
const PREVIEW =
  "Marketing is a preview: it shows sample data and isn't connected to the server yet. Anything you add here is gone when you reload the page, so keep real campaign work elsewhere for now.";

const marketing = [
  {
    path: "/marketing/dashboard",
    title: "Marketing Dashboard",
    purpose: "An overview of campaigns and the leads they bring in. " + PREVIEW,
    sections: [
      { heading: "Key figures", body: "Active Campaigns, Leads Generated by all campaigns, Conversion Rate (the share of those leads that became customers) and Form Submissions." },
      { heading: "Charts", body: "Leads by Channel shows which channel (email, social, search, events, referrals) brings the most leads. Campaigns by Status splits campaigns into Draft, Active, Paused and Completed." },
      { heading: "Lists", body: "Campaigns Ending Soon shows active campaigns with the nearest end date. Segments shows your customer groups and their size." },
    ],
    tour: [
      { target: "marketing-kpis", title: "Marketing at a glance", body: "Active campaigns, leads generated, conversion rate and form submissions." },
      { target: "marketing-charts", title: "What works", body: "Leads per channel and campaigns per status." },
      { target: "marketing-lists", title: "Coming up", body: "Campaigns about to end and your customer segments." },
    ],
  },
  {
    path: "/marketing/campaigns",
    title: "Campaigns",
    purpose: "A campaign is one marketing push, such as a newsletter, an event or an ad run, with a budget and a target number of leads. " + PREVIEW,
    sections: [
      { heading: "Creating a campaign", body: "New Campaign asks for a name, the channel, the budget and the lead goal: how many leads you hope it brings." },
      { heading: "The list", body: "Leads Generated shows leads so far against the goal. Converted counts those that became customers. Click a campaign to open it." },
    ],
    tour: [
      { target: "campaigns-add", title: "Start a campaign", body: "Name it, pick the channel, and set a budget and a lead goal." },
      { target: "campaigns-table", title: "Your campaigns", body: "Leads against the goal, conversions, budget and status. Click one to open it." },
    ],
  },
  {
    path: "/marketing/campaigns/:id",
    title: "Campaign",
    purpose: "One campaign's results: leads generated, conversions and progress towards its goal. " + PREVIEW,
    sections: [
      { heading: "Status", body: "Draft while you prepare it, Active while it runs, Paused to stop it for a while, Completed when it is over." },
      { heading: "Results", body: "Leads Generated, Converted, and Goal Progress: leads so far as a share of the goal." },
      { heading: "Attributed leads", body: "The leads that came from this campaign. Click one to open it in CRM." },
    ],
    tour: [
      { target: "campaign-status", title: "Campaign status", body: "Set it to Draft, Active, Paused or Completed." },
      { target: "campaign-kpis", title: "Results", body: "Leads generated, conversions and progress towards the goal." },
      { target: "campaign-leads", title: "Leads from this campaign", body: "Click a lead to open it in CRM." },
    ],
  },
  {
    path: "/marketing/segments",
    title: "Segments",
    purpose: "A segment is a group of customers who share something, for example every company in one industry, so you can target them together. " + PREVIEW,
    sections: [
      { heading: "Creating a segment", body: "New Segment asks for a name and a rule: companies of one industry, or of one account type (Prospect, Customer, Partner, Vendor, Former Customer)." },
      { heading: "Size", body: "Each card shows how many contacts belong to the segment. Members are worked out from the rule, so the number changes as companies change." },
      { heading: "Deleting", body: "The bin icon deletes a segment. The companies and contacts in it are not touched." },
    ],
    tour: [
      { target: "segments-add", title: "Create a segment", body: "Name a group and choose the rule that decides who is in it." },
      { target: "segments-cards", title: "Your segments", body: "Each card shows the rule and how many contacts match it." },
    ],
  },
  {
    path: "/marketing/forms",
    title: "Lead-Capture Forms",
    purpose: "A form collects name, email and company from visitors, for example on your website, and turns each submission into a lead. " + PREVIEW,
    sections: [
      { heading: "Creating a form", body: "New Form asks for a name and, optionally, the campaign the leads should count towards." },
      { heading: "Trying it out", body: "Simulate Submission fills in the form as a visitor would, so you can see how it counts. In this preview the lead is not added to your CRM." },
    ],
    tour: [
      { target: "forms-add", title: "Create a form", body: "Name it and link it to a campaign." },
      { target: "forms-cards", title: "Your forms", body: "Each card shows the fields and the number of submissions. Use Simulate Submission to try it." },
    ],
  },
  {
    path: "/marketing/templates",
    title: "Templates",
    purpose: "Reusable email texts with a subject and a body, so everyone sends the same well-written message. " + PREVIEW,
    sections: [
      { heading: "Creating a template", body: "New Template asks for a name, a subject and the message. Write {{name}} where the person's name should go." },
      { heading: "Sending", body: "Templates are for writing only; nothing is emailed from here. Copy the text into your email." },
    ],
    tour: [
      { target: "templates-add", title: "Write a template", body: "Give it a name, a subject and the message text." },
      { target: "templates-cards", title: "Your templates", body: "Each card shows the subject and the start of the message." },
    ],
  },
];

export default marketing;
