import { Router } from "express";
import { authenticate } from "../middleware/auth.js";
import { asyncHandler } from "../utils/crudFactory.js";
import { listProviderStatuses } from "../services/ai/providerRegistry.js";
import { generateNarrative, generateExploration } from "../services/ai/aiGatewayService.js";
import { checkCooldown } from "../services/ai/guardrails.js";
import { narrativeRequestSchema, exploreRequestSchema } from "../services/ai/schemas.js";

const router = Router();
router.use(authenticate);

router.get("/providers", asyncHandler(async (_req, res) => {
  res.json({ providers: listProviderStatuses() });
}));

router.post("/narrative", asyncHandler(async (req, res) => {
  const parsed = narrativeRequestSchema.safeParse(req.body);
  if (!parsed.success) return res.status(400).json({ message: parsed.error.issues[0]?.message || "Invalid request" });

  checkCooldown(req.user.id);
  const result = await generateNarrative({
    providerId: parsed.data.provider, executiveSummary: parsed.data.executiveSummary, facts: parsed.data.facts,
  });
  res.json({
    narrative: result.narrative, numbersVerified: result.numbersVerified, provider: result.provider,
    generatedAt: new Date().toISOString(),
  });
}));

router.post("/explore", asyncHandler(async (req, res) => {
  const parsed = exploreRequestSchema.safeParse(req.body);
  if (!parsed.success) return res.status(400).json({ message: parsed.error.issues[0]?.message || "Invalid request" });

  checkCooldown(req.user.id);
  const result = await generateExploration({
    providerId: parsed.data.provider, role: req.user.role, scopeLabel: parsed.data.scopeLabel,
    question: parsed.data.question, records: parsed.data.records,
  });
  res.json({
    findings: result.findings, truncated: result.truncated, provider: result.provider,
    generatedAt: new Date().toISOString(),
    disclaimer: `Generated by ${result.provider.label} (${result.provider.model}) reasoning directly over your current records. Not verified by the deterministic engine — figures and conclusions here may be wrong. Always confirm before acting.`,
  });
}));

export default router;
