import { describe, it, expect, beforeEach, vi } from "vitest";
import { configureStore } from "@reduxjs/toolkit";

const mockRequestExploration = vi.fn();
vi.mock("../../pages/AI/aiGatewayClient", () => ({
  requestExploration: (...args) => mockRequestExploration(...args),
}));

import aiExploreReducer, { runExploration, clearExploration, selectAiExplore } from "./aiExploreSlice";
import authReducer from "../authSlice";
import leadsReducer from "../crm/leadsSlice";
import companiesReducer from "../crm/companiesSlice";
import contactsReducer from "../crm/contactsSlice";
import dealsReducer from "../crm/dealsSlice";
import activitiesReducer from "../crm/activitiesSlice";
import quotesReducer from "../sales/quotesSlice";
import ordersReducer from "../sales/ordersSlice";
import contractsReducer from "../sales/contractsSlice";

function makeStore(role = "Super-Admin") {
  localStorage.setItem("role", role);
  localStorage.setItem("isLoggedIn", "true");
  return configureStore({
    reducer: {
      auth: authReducer, aiExplore: aiExploreReducer, leads: leadsReducer, companies: companiesReducer, contacts: contactsReducer,
      deals: dealsReducer, activities: activitiesReducer, quotes: quotesReducer, orders: ordersReducer, contracts: contractsReducer,
    },
    preloadedState: { auth: { role, isLoggedIn: true, data: {} } },
  });
}

describe("aiExploreSlice — session-only Explore Mode state", () => {
  beforeEach(() => {
    localStorage.clear();
    mockRequestExploration.mockReset();
  });

  it("starts idle with no findings", () => {
    const store = makeStore();
    expect(selectAiExplore(store.getState())).toEqual({ status: "idle", findings: [], error: null });
  });

  it("a successful run prepends a findings entry with real AIInsight objects and the backend's disclaimer", async () => {
    mockRequestExploration.mockResolvedValue({
      findings: [{ title: "Stalled deal", observation: "Idle 20 days.", citedRecordIds: [] }],
      truncated: false,
      provider: { id: "anthropic", label: "Anthropic (Claude)", model: "claude-haiku-4-5-20251001" },
      disclaimer: "Generated by Anthropic (Claude) — unverified.",
      generatedAt: "2026-01-01T00:00:00.000Z",
    });
    const store = makeStore();
    await store.dispatch(runExploration({ question: "What deals are at risk?" }));

    const state = selectAiExplore(store.getState());
    expect(state.status).toBe("idle");
    expect(state.findings).toHaveLength(1);
    const run = state.findings[0];
    expect(run.question).toBe("What deals are at risk?");
    expect(run.disclaimer).toBe("Generated by Anthropic (Claude) — unverified.");
    expect(run.provider.id).toBe("anthropic");
    expect(run.insights).toHaveLength(1);
    expect(run.insights[0].title).toBe("Unverified: Stalled deal");
    expect(run.insights[0].confidence.level).toBe("Insufficient Data");
  });

  it("passes the request's provider id and question straight through to requestExploration", async () => {
    mockRequestExploration.mockResolvedValue({ findings: [], truncated: false, provider: { id: "openai", label: "OpenAI", model: "m" }, disclaimer: "d", generatedAt: "now" });
    const store = makeStore();
    await store.dispatch(runExploration({ question: "Anything interesting?", providerId: "openai" }));
    expect(mockRequestExploration).toHaveBeenCalledWith(expect.objectContaining({ provider: "openai", question: "Anything interesting?" }));
  });

  it("multiple runs accumulate, newest first", async () => {
    mockRequestExploration
      .mockResolvedValueOnce({ findings: [], truncated: false, provider: { id: "anthropic", label: "A", model: "m" }, disclaimer: "d1", generatedAt: "now" })
      .mockResolvedValueOnce({ findings: [], truncated: false, provider: { id: "anthropic", label: "A", model: "m" }, disclaimer: "d2", generatedAt: "now" });
    const store = makeStore();
    await store.dispatch(runExploration({ question: "first" }));
    await store.dispatch(runExploration({ question: "second" }));
    const { findings } = selectAiExplore(store.getState());
    expect(findings).toHaveLength(2);
    expect(findings[0].question).toBe("second"); // newest first
    expect(findings[1].question).toBe("first");
  });

  it("a truncated response is reflected on the run entry", async () => {
    mockRequestExploration.mockResolvedValue({ findings: [], truncated: true, provider: { id: "anthropic", label: "A", model: "m" }, disclaimer: "d", generatedAt: "now" });
    const store = makeStore();
    await store.dispatch(runExploration({}));
    expect(selectAiExplore(store.getState()).findings[0].truncated).toBe(true);
  });

  it("a failed request lands on error with a message and does not add a findings entry", async () => {
    mockRequestExploration.mockRejectedValue({ response: { data: { message: "No AI provider is configured on this server." } } });
    const store = makeStore();
    await store.dispatch(runExploration({ question: "x" }));
    const state = selectAiExplore(store.getState());
    expect(state.status).toBe("error");
    expect(state.error).toBe("No AI provider is configured on this server.");
    expect(state.findings).toEqual([]);
  });

  it("clearExploration resets findings, status and error", async () => {
    mockRequestExploration.mockResolvedValue({ findings: [], truncated: false, provider: { id: "anthropic", label: "A", model: "m" }, disclaimer: "d", generatedAt: "now" });
    const store = makeStore();
    await store.dispatch(runExploration({}));
    expect(selectAiExplore(store.getState()).findings).toHaveLength(1);
    store.dispatch(clearExploration());
    expect(selectAiExplore(store.getState())).toEqual({ status: "idle", findings: [], error: null });
  });

  it("Auditor/Checker — who the mock API blocks from CRM/Sales endpoints — still resolves instead of failing the whole run", async () => {
    mockRequestExploration.mockResolvedValue({ findings: [], truncated: false, provider: { id: "anthropic", label: "A", model: "m" }, disclaimer: "d", generatedAt: "now" });
    const store = makeStore("Checker");
    await store.dispatch(runExploration({ question: "x" }));
    expect(selectAiExplore(store.getState()).status).toBe("idle");
  });
});
