// The built-in roles and their permission grants, shared by prisma/seed.js
// (dev data) and scripts/seedRoles.js (roles only — safe for production).
//
// Built-in roles matching the frontend's RBAC preview role templates —
// `key` links each row to the real auth role identifier it maps to.
// permissionGrants: [{moduleId, actions:[]}] against constants/
// permissionCatalog.js's "platform" module group (organizations, members,
// invitations, invite_links, sessions, audit_events) — Backend Phase 1's
// org-scoped RBAC surface. Auditor/Checker is read-only by design: no
// grant here ever includes an edit/create/assign/delete_permanently
// action. Standard Employee gets nothing (deny by default).
export const BUILT_IN_ROLES = [
  {
    key: "super_admin", name: "System Owner", defaultScope: "System-wide", purpose: "Highest system-level authority.",
    permissionGrants: [
      { moduleId: "organizations", actions: ["view", "edit"] },
      { moduleId: "members", actions: ["view", "edit", "assign", "delete_permanently"] },
      { moduleId: "invitations", actions: ["view", "create", "edit"] },
      { moduleId: "invite_links", actions: ["view", "create", "edit"] },
      { moduleId: "sessions", actions: ["view"] },
      { moduleId: "audit_events", actions: ["view"] },
      // Backend Phase 2 — CRM Core Data Persistence
      { moduleId: "leads", actions: ["view", "create", "edit", "assign", "archive", "restore", "convert", "bulk_actions", "export"] },
      { moduleId: "contacts", actions: ["view", "create", "edit", "assign", "archive", "restore", "merge", "bulk_actions", "export", "view_sensitive_fields"] },
      { moduleId: "companies", actions: ["view", "create", "edit", "assign", "archive", "restore", "merge", "bulk_actions", "export", "view_financial_fields"] },
      { moduleId: "activities", actions: ["view", "create", "edit", "assign", "archive", "restore", "bulk_actions"] },
      { moduleId: "notes", actions: ["view", "create", "edit", "archive"] },
      { moduleId: "tags", actions: ["view", "create", "edit", "archive"] },
      // Backend Phase 3 — Sales Pipeline, Deals, Catalog, Quotes, Orders, Contracts
      { moduleId: "pipeline", actions: ["view", "create", "edit", "archive", "restore", "reorder"] },
      { moduleId: "deals", actions: ["view", "create", "edit", "assign", "transition", "close", "reopen", "archive", "restore", "bulk_actions", "view_financial_fields"] },
      { moduleId: "products_services", actions: ["view", "create", "edit", "archive", "restore", "view_financial_fields"] },
      { moduleId: "price_books", actions: ["view", "create", "edit", "archive", "restore"] },
      { moduleId: "quotes", actions: ["view", "create", "edit", "submit", "approve", "reject", "issue", "accept", "cancel", "archive", "restore", "bulk_actions", "override_pricing", "view_financial_fields"] },
      { moduleId: "orders", actions: ["view", "create", "edit", "confirm", "cancel", "fulfill", "archive", "restore", "bulk_actions"] },
      { moduleId: "contracts", actions: ["view", "create", "edit", "approve", "activate", "renew", "terminate", "manage_obligations", "archive", "restore", "bulk_actions"] },
      { moduleId: "sales_reports", actions: ["view", "view_forecast"] },
      // Backend Phase 4 — Support (full spec)
      { moduleId: "tickets", actions: ["view", "create", "edit", "assign", "transition", "resolve", "close", "reopen", "archive", "restore", "merge", "bulk_actions", "reply", "escalate", "view_internal_notes", "add_internal_notes", "view_restricted_notes", "view_audit_history"] },
      { moduleId: "support_inboxes", actions: ["view", "configure"] },
      { moduleId: "support_queues", actions: ["view", "configure"] },
      { moduleId: "support_sla", actions: ["view", "configure"] },
      { moduleId: "support_entitlements", actions: ["view", "configure"] },
      { moduleId: "knowledge_base", actions: ["view", "create", "review", "publish", "archive"] },
      { moduleId: "canned_responses", actions: ["view", "configure"] },
      { moduleId: "support_csat", actions: ["view"] },
      { moduleId: "support_reports", actions: ["view"] },
      { moduleId: "support_portal", actions: ["view", "configure"] },
      // Backend Phase 5 — Projects (full spec)
      { moduleId: "projects", actions: ["view", "create", "edit", "transition", "reopen", "archive", "restore", "manage_members", "assign", "view_financial_fields", "view_audit_history", "override_progress"] },
      { moduleId: "tasks", actions: ["view", "create", "edit", "assign", "transition", "archive", "restore", "bulk_actions"] },
      { moduleId: "project_portfolios", actions: ["view", "configure"] },
      { moduleId: "project_templates", actions: ["view", "configure"] },
      { moduleId: "project_planning", actions: ["configure"] },
      { moduleId: "project_time", actions: ["view_own", "view_team", "create", "submit", "approve", "correct"] },
      { moduleId: "deliverables", actions: ["view", "edit", "review", "accept"] },
      { moduleId: "project_risks", actions: ["view", "edit", "accept"] },
      { moduleId: "project_issues", actions: ["view", "edit"] },
      { moduleId: "change_requests", actions: ["view", "create", "review", "apply"] },
      { moduleId: "project_baselines", actions: ["view", "create"] },
      { moduleId: "project_reports", actions: ["view"] },
      // Backend Phase 6 (full spec) — Finance. Still audited; override_controls is the emergency override.
      { moduleId: "invoices", actions: ["view", "create", "edit", "submit", "approve", "post", "issue", "cancel", "credit", "view_audit_history"] },
      { moduleId: "credit_notes", actions: ["view", "create", "approve", "post"] },
      { moduleId: "payments", actions: ["view", "create", "approve", "post", "reverse", "allocate"] },
      { moduleId: "expenses", actions: ["view", "create", "submit", "approve", "reject", "approve_exception", "post", "reimburse", "view_audit_history"] },
      { moduleId: "recurring_invoices", actions: ["view", "create", "edit"] },
      { moduleId: "finance_configuration", actions: ["view", "configure", "approve"] },
      { moduleId: "fiscal_periods", actions: ["view", "configure", "close", "reopen", "post"] },
      { moduleId: "ledger_accounts", actions: ["view", "configure"] },
      { moduleId: "journals", actions: ["view", "create", "approve", "post", "reverse"] },
      { moduleId: "vendors", actions: ["view", "configure"] },
      { moduleId: "bills", actions: ["view", "create", "edit", "submit", "approve", "post", "cancel"] },
      { moduleId: "financial_accounts", actions: ["view", "configure", "view_sensitive_fields"] },
      { moduleId: "reconciliation", actions: ["view", "create", "approve"] },
      { moduleId: "budgets", actions: ["view", "create", "approve", "activate"] },
      { moduleId: "finance_reports", actions: ["view"] },
      { moduleId: "finance_overrides", actions: ["view", "override_controls"] },
      // Backend Phase 8 — Integrations. Manages provider availability; never sees decrypted tokens.
      { moduleId: "integration_catalog", actions: ["view", "configure"] },
      { moduleId: "integration_connections", actions: ["view", "create_user", "create_organization", "edit", "reauthorize", "disconnect", "view_sensitive_fields"] },
      { moduleId: "integration_scopes", actions: ["view"] },
      { moduleId: "integration_policies", actions: ["view", "configure"] },
      { moduleId: "integration_sync", actions: ["view", "configure", "preview", "execute", "cancel"] },
      { moduleId: "integration_conflicts", actions: ["view", "resolve"] },
      { moduleId: "integration_webhooks", actions: ["view", "configure"] },
      { moduleId: "integration_outbound_webhooks", actions: ["view", "configure"] },
      { moduleId: "integration_logs", actions: ["view"] },
      { moduleId: "integration_credentials", actions: ["rotate"] },
      { moduleId: "integration_audit", actions: ["view"] },
      // Backend Phase 9 — AI. Platform AI catalog and policies; tenant AI data only through organization membership.
      { moduleId: "ai_providers", actions: ["view","configure","rotate"] },
      { moduleId: "ai_models", actions: ["view","configure"] },
      { moduleId: "ai_routing", actions: ["view","configure"] },
      { moduleId: "ai_policies", actions: ["view","configure"] },
      { moduleId: "ai_usage", actions: ["view_own","view_organization"] },
      { moduleId: "ai_budgets", actions: ["view","configure"] },
      { moduleId: "ai_features", actions: ["use"] },
      { moduleId: "ai_actions", actions: ["view","propose","confirm","approve"] },
      { moduleId: "ai_evaluations", actions: ["view","execute"] },
      { moduleId: "ai_audit", actions: ["view"] },
      // Backend Phase 10 — AI Copilot. Copilot platform policy, tools, templates and index; tenant data only through membership.
      { moduleId: "ai_copilot", actions: ["use"] },
      { moduleId: "ai_copilot_conversations", actions: ["view_own","view_audit_history"] },
      { moduleId: "ai_copilot_memory", actions: ["configure"] },
      { moduleId: "ai_copilot_tools", actions: ["view","view_sensitive_fields"] },
      { moduleId: "ai_copilot_workflows", actions: ["execute","approve"] },
      { moduleId: "ai_copilot_index", actions: ["configure"] },
      { moduleId: "ai_copilot_policy", actions: ["configure"] },
    ],
  },
  {
    key: "admin", name: "Organization Administrator", defaultScope: "Organization", purpose: "Manages one organization and its business configuration.",
    permissionGrants: [
      { moduleId: "organizations", actions: ["view", "edit"] },
      { moduleId: "members", actions: ["view", "edit", "assign", "delete_permanently"] },
      { moduleId: "invitations", actions: ["view", "create", "edit"] },
      { moduleId: "invite_links", actions: ["view", "create", "edit"] },
      { moduleId: "sessions", actions: ["view"] },
      { moduleId: "audit_events", actions: ["view"] },
      { moduleId: "leads", actions: ["view", "create", "edit", "assign", "archive", "restore", "convert", "bulk_actions", "export"] },
      { moduleId: "contacts", actions: ["view", "create", "edit", "assign", "archive", "restore", "merge", "bulk_actions", "export", "view_sensitive_fields"] },
      { moduleId: "companies", actions: ["view", "create", "edit", "assign", "archive", "restore", "merge", "bulk_actions", "export", "view_financial_fields"] },
      { moduleId: "activities", actions: ["view", "create", "edit", "assign", "archive", "restore", "bulk_actions"] },
      { moduleId: "notes", actions: ["view", "create", "edit", "archive"] },
      { moduleId: "tags", actions: ["view", "create", "edit", "archive"] },
      { moduleId: "pipeline", actions: ["view", "create", "edit", "archive", "restore", "reorder"] },
      { moduleId: "deals", actions: ["view", "create", "edit", "assign", "transition", "close", "reopen", "archive", "restore", "bulk_actions", "view_financial_fields"] },
      { moduleId: "products_services", actions: ["view", "create", "edit", "archive", "restore", "view_financial_fields"] },
      { moduleId: "price_books", actions: ["view", "create", "edit", "archive", "restore"] },
      { moduleId: "quotes", actions: ["view", "create", "edit", "submit", "approve", "reject", "issue", "accept", "cancel", "archive", "restore", "bulk_actions", "override_pricing", "view_financial_fields"] },
      { moduleId: "orders", actions: ["view", "create", "edit", "confirm", "cancel", "fulfill", "archive", "restore", "bulk_actions"] },
      { moduleId: "contracts", actions: ["view", "create", "edit", "approve", "activate", "renew", "terminate", "manage_obligations", "archive", "restore", "bulk_actions"] },
      { moduleId: "sales_reports", actions: ["view", "view_forecast"] },
      // Backend Phase 4 — Support (full spec)
      { moduleId: "tickets", actions: ["view", "create", "edit", "assign", "transition", "resolve", "close", "reopen", "archive", "restore", "merge", "bulk_actions", "reply", "escalate", "view_internal_notes", "add_internal_notes", "view_restricted_notes", "view_audit_history"] },
      { moduleId: "support_inboxes", actions: ["view", "configure"] },
      { moduleId: "support_queues", actions: ["view", "configure"] },
      { moduleId: "support_sla", actions: ["view", "configure"] },
      { moduleId: "support_entitlements", actions: ["view", "configure"] },
      { moduleId: "knowledge_base", actions: ["view", "create", "review", "publish", "archive"] },
      { moduleId: "canned_responses", actions: ["view", "configure"] },
      { moduleId: "support_csat", actions: ["view"] },
      { moduleId: "support_reports", actions: ["view"] },
      { moduleId: "support_portal", actions: ["view", "configure"] },
      // Backend Phase 5 — Projects (full spec)
      { moduleId: "projects", actions: ["view", "create", "edit", "transition", "reopen", "archive", "restore", "manage_members", "assign", "view_financial_fields", "view_audit_history", "override_progress"] },
      { moduleId: "tasks", actions: ["view", "create", "edit", "assign", "transition", "archive", "restore", "bulk_actions"] },
      { moduleId: "project_portfolios", actions: ["view", "configure"] },
      { moduleId: "project_templates", actions: ["view", "configure"] },
      { moduleId: "project_planning", actions: ["configure"] },
      { moduleId: "project_time", actions: ["view_own", "view_team", "create", "submit", "approve", "correct"] },
      { moduleId: "deliverables", actions: ["view", "edit", "review", "accept"] },
      { moduleId: "project_risks", actions: ["view", "edit", "accept"] },
      { moduleId: "project_issues", actions: ["view", "edit"] },
      { moduleId: "change_requests", actions: ["view", "create", "review", "apply"] },
      { moduleId: "project_baselines", actions: ["view", "create"] },
      { moduleId: "project_reports", actions: ["view"] },
      // Backend Phase 6 (full spec) — Finance: configures, approves documents; posting, payments and period close stay with Finance roles.
      { moduleId: "invoices", actions: ["view", "create", "edit", "submit", "approve", "issue", "cancel", "credit"] },
      { moduleId: "credit_notes", actions: ["view", "create", "approve"] },
      { moduleId: "payments", actions: ["view"] },
      { moduleId: "expenses", actions: ["view", "create", "submit", "approve", "reject"] },
      { moduleId: "recurring_invoices", actions: ["view", "create", "edit"] },
      { moduleId: "finance_configuration", actions: ["view", "configure", "approve"] },
      { moduleId: "fiscal_periods", actions: ["view", "configure"] },
      { moduleId: "ledger_accounts", actions: ["view", "configure"] },
      { moduleId: "journals", actions: ["view"] },
      { moduleId: "vendors", actions: ["view", "configure"] },
      { moduleId: "bills", actions: ["view", "create", "edit", "submit", "approve"] },
      { moduleId: "financial_accounts", actions: ["view", "configure"] },
      { moduleId: "reconciliation", actions: ["view"] },
      { moduleId: "budgets", actions: ["view", "create", "approve"] },
      { moduleId: "finance_reports", actions: ["view"] },
      { moduleId: "finance_overrides", actions: ["view"] },
      // Backend Phase 8 — Integrations: organization connections and policies within system policy.
      { moduleId: "integration_catalog", actions: ["view"] },
      { moduleId: "integration_connections", actions: ["view", "create_user", "create_organization", "edit", "reauthorize", "disconnect", "view_sensitive_fields"] },
      { moduleId: "integration_scopes", actions: ["view"] },
      { moduleId: "integration_policies", actions: ["view", "configure"] },
      { moduleId: "integration_sync", actions: ["view", "configure", "preview", "execute", "cancel"] },
      { moduleId: "integration_conflicts", actions: ["view", "resolve"] },
      { moduleId: "integration_webhooks", actions: ["view", "configure"] },
      { moduleId: "integration_outbound_webhooks", actions: ["view", "configure"] },
      { moduleId: "integration_logs", actions: ["view"] },
      { moduleId: "integration_credentials", actions: ["rotate"] },
      { moduleId: "integration_audit", actions: ["view"] },
      // Backend Phase 9 — AI. Organization AI connections, keys, policies, routing, budgets, usage and evaluations.
      { moduleId: "ai_providers", actions: ["view","configure","rotate"] },
      { moduleId: "ai_models", actions: ["view","configure"] },
      { moduleId: "ai_routing", actions: ["view","configure"] },
      { moduleId: "ai_policies", actions: ["view","configure"] },
      { moduleId: "ai_usage", actions: ["view_own","view_organization"] },
      { moduleId: "ai_budgets", actions: ["view","configure"] },
      { moduleId: "ai_features", actions: ["use"] },
      { moduleId: "ai_actions", actions: ["view","propose","confirm","approve"] },
      { moduleId: "ai_evaluations", actions: ["view","execute"] },
      { moduleId: "ai_audit", actions: ["view"] },
      // Backend Phase 10 — AI Copilot. Copilot policy, index, memory rules, usage and audited conversation review.
      { moduleId: "ai_copilot", actions: ["use"] },
      { moduleId: "ai_copilot_conversations", actions: ["view_own","view_audit_history"] },
      { moduleId: "ai_copilot_memory", actions: ["configure"] },
      { moduleId: "ai_copilot_tools", actions: ["view","view_sensitive_fields"] },
      { moduleId: "ai_copilot_workflows", actions: ["execute","approve"] },
      { moduleId: "ai_copilot_index", actions: ["configure"] },
      { moduleId: "ai_copilot_policy", actions: ["configure"] },
    ],
  },
  {
    key: "team_leader", name: "Department Manager", defaultScope: "Department", purpose: "Manages employees and records within one department.",
    permissionGrants: [
      { moduleId: "members", actions: ["view"] },
      // Department-scoped — the actual department filter is applied by
      // the controller using this role's defaultScope, not by the grant
      // itself (permissionGrants only ever says WHICH actions, never
      // WHICH records; scope is a separate dimension on the Role).
      { moduleId: "leads", actions: ["view", "create", "edit", "assign", "archive"] },
      { moduleId: "contacts", actions: ["view", "create", "edit", "assign", "archive"] },
      { moduleId: "companies", actions: ["view", "create", "edit", "assign", "archive"] },
      { moduleId: "activities", actions: ["view", "create", "edit", "assign", "archive", "restore"] },
      { moduleId: "notes", actions: ["view", "create", "edit"] },
      { moduleId: "tags", actions: ["view", "edit"] },
      // Sales Manager-equivalent: full deal lifecycle within their
      // department, no override_pricing/approve (separation of duties
      // keeps Quote approval with Organization Administrator+), no
      // Pipeline structural changes (create/archive) or Contract
      // activation/termination.
      { moduleId: "pipeline", actions: ["view", "edit", "reorder"] },
      { moduleId: "deals", actions: ["view", "create", "edit", "assign", "transition", "close", "reopen", "archive"] },
      { moduleId: "products_services", actions: ["view"] },
      { moduleId: "price_books", actions: ["view"] },
      { moduleId: "quotes", actions: ["view", "create", "edit", "submit", "accept", "cancel"] },
      { moduleId: "orders", actions: ["view", "create", "edit", "confirm", "cancel"] },
      { moduleId: "contracts", actions: ["view", "create", "edit"] },
      { moduleId: "sales_reports", actions: ["view"] },
      // Support manager-equivalent: runs queues, reviews and publishes KB articles.
      { moduleId: "tickets", actions: ["view", "create", "edit", "assign", "transition", "resolve", "close", "reopen", "archive", "restore", "merge", "bulk_actions", "reply", "escalate", "view_internal_notes", "add_internal_notes", "view_restricted_notes"] },
      { moduleId: "support_inboxes", actions: ["view"] },
      { moduleId: "support_queues", actions: ["view", "configure"] },
      { moduleId: "support_sla", actions: ["view"] },
      { moduleId: "support_entitlements", actions: ["view"] },
      { moduleId: "knowledge_base", actions: ["view", "create", "review", "publish"] },
      { moduleId: "canned_responses", actions: ["view", "configure"] },
      { moduleId: "support_csat", actions: ["view"] },
      { moduleId: "support_reports", actions: ["view"] },
      { moduleId: "support_portal", actions: ["view"] },
      // Project manager-equivalent: runs projects, approves team time.
      { moduleId: "projects", actions: ["view", "create", "edit", "transition", "reopen", "archive", "restore", "manage_members", "assign", "view_financial_fields", "override_progress"] },
      { moduleId: "tasks", actions: ["view", "create", "edit", "assign", "transition", "archive", "restore", "bulk_actions"] },
      { moduleId: "project_portfolios", actions: ["view"] },
      { moduleId: "project_templates", actions: ["view", "configure"] },
      { moduleId: "project_planning", actions: ["configure"] },
      { moduleId: "project_time", actions: ["view_own", "view_team", "create", "submit", "approve", "correct"] },
      { moduleId: "deliverables", actions: ["view", "edit", "review", "accept"] },
      { moduleId: "project_risks", actions: ["view", "edit", "accept"] },
      { moduleId: "project_issues", actions: ["view", "edit"] },
      { moduleId: "change_requests", actions: ["view", "create", "review", "apply"] },
      { moduleId: "project_baselines", actions: ["view", "create"] },
      { moduleId: "project_reports", actions: ["view"] },
      // Finance: prepares draft invoices, reviews the department's expenses and drafts department budgets; approving, posting and paying stay with Finance roles.
      { moduleId: "invoices", actions: ["view", "create", "edit", "submit"] },
      { moduleId: "payments", actions: ["view"] },
      { moduleId: "expenses", actions: ["view", "create", "submit", "approve", "reject"] },
      { moduleId: "recurring_invoices", actions: ["view"] },
      { moduleId: "budgets", actions: ["view", "create"] },
      // Integrations: department connections and the sync for modules this role manages (checked per capability).
      { moduleId: "integration_catalog", actions: ["view"] },
      { moduleId: "integration_connections", actions: ["view", "create_user", "edit", "reauthorize", "disconnect"] },
      { moduleId: "integration_scopes", actions: ["view"] },
      { moduleId: "integration_policies", actions: ["view"] },
      { moduleId: "integration_sync", actions: ["view", "configure", "preview", "execute", "cancel"] },
      { moduleId: "integration_conflicts", actions: ["view", "resolve"] },
      { moduleId: "integration_webhooks", actions: ["view"] },
      { moduleId: "integration_logs", actions: ["view"] },
      // Backend Phase 9 — AI. Uses AI within department scope; confirms and approves action proposals in scope.
      { moduleId: "ai_providers", actions: ["view"] },
      { moduleId: "ai_models", actions: ["view"] },
      { moduleId: "ai_usage", actions: ["view_own"] },
      { moduleId: "ai_features", actions: ["use"] },
      { moduleId: "ai_actions", actions: ["view","propose","confirm","approve"] },
      { moduleId: "ai_evaluations", actions: ["view"] },
      // Backend Phase 10 — AI Copilot. Copilot in department scope; runs and approves workflows.
      { moduleId: "ai_copilot", actions: ["use"] },
      { moduleId: "ai_copilot_conversations", actions: ["view_own"] },
      { moduleId: "ai_copilot_memory", actions: ["configure"] },
      { moduleId: "ai_copilot_tools", actions: ["view"] },
      { moduleId: "ai_copilot_workflows", actions: ["execute","approve"] },
    ],
  },
  {
    key: "checker", name: "Auditor / Checker", defaultScope: "Organization", purpose: "Performs independent review and compliance checking.",
    permissionGrants: [
      { moduleId: "organizations", actions: ["view"] },
      { moduleId: "members", actions: ["view"] },
      { moduleId: "invitations", actions: ["view"] },
      { moduleId: "invite_links", actions: ["view"] },
      { moduleId: "sessions", actions: ["view"] },
      { moduleId: "audit_events", actions: ["view"] },
      // Read-only by design — no grant below ever includes create/edit/
      // assign/archive/restore/convert/merge/bulk_actions.
      { moduleId: "leads", actions: ["view", "view_audit_history"] },
      { moduleId: "contacts", actions: ["view", "view_audit_history"] },
      { moduleId: "companies", actions: ["view", "view_audit_history"] },
      { moduleId: "activities", actions: ["view", "view_audit_history"] },
      { moduleId: "notes", actions: ["view"] },
      { moduleId: "tags", actions: ["view"] },
      { moduleId: "pipeline", actions: ["view", "view_audit_history"] },
      { moduleId: "deals", actions: ["view", "view_audit_history"] },
      { moduleId: "products_services", actions: ["view"] },
      { moduleId: "price_books", actions: ["view"] },
      { moduleId: "quotes", actions: ["view", "view_audit_history"] },
      { moduleId: "orders", actions: ["view", "view_audit_history"] },
      { moduleId: "contracts", actions: ["view", "view_audit_history"] },
      { moduleId: "sales_reports", actions: ["view", "view_forecast"] },
      { moduleId: "tickets", actions: ["view", "view_internal_notes", "view_restricted_notes", "view_audit_history"] },
      { moduleId: "support_inboxes", actions: ["view"] },
      { moduleId: "support_queues", actions: ["view"] },
      { moduleId: "support_sla", actions: ["view"] },
      { moduleId: "support_entitlements", actions: ["view"] },
      { moduleId: "knowledge_base", actions: ["view"] },
      { moduleId: "canned_responses", actions: ["view"] },
      { moduleId: "support_csat", actions: ["view"] },
      { moduleId: "support_reports", actions: ["view"] },
      { moduleId: "support_portal", actions: ["view"] },
      { moduleId: "projects", actions: ["view", "view_audit_history", "view_financial_fields"] },
      { moduleId: "tasks", actions: ["view"] },
      { moduleId: "project_portfolios", actions: ["view"] },
      { moduleId: "project_templates", actions: ["view"] },
      { moduleId: "project_time", actions: ["view_own", "view_team"] },
      { moduleId: "deliverables", actions: ["view"] },
      { moduleId: "project_risks", actions: ["view"] },
      { moduleId: "project_issues", actions: ["view"] },
      { moduleId: "change_requests", actions: ["view"] },
      { moduleId: "project_baselines", actions: ["view"] },
      { moduleId: "project_reports", actions: ["view"] },
      // Finance: read-only everywhere, including overrides.
      { moduleId: "invoices", actions: ["view", "view_audit_history"] },
      { moduleId: "credit_notes", actions: ["view"] },
      { moduleId: "payments", actions: ["view"] },
      { moduleId: "expenses", actions: ["view", "view_audit_history"] },
      { moduleId: "recurring_invoices", actions: ["view"] },
      { moduleId: "finance_configuration", actions: ["view"] },
      { moduleId: "fiscal_periods", actions: ["view"] },
      { moduleId: "ledger_accounts", actions: ["view"] },
      { moduleId: "journals", actions: ["view", "view_audit_history"] },
      { moduleId: "vendors", actions: ["view"] },
      { moduleId: "bills", actions: ["view"] },
      { moduleId: "financial_accounts", actions: ["view", "view_sensitive_fields"] },
      { moduleId: "reconciliation", actions: ["view"] },
      { moduleId: "budgets", actions: ["view"] },
      { moduleId: "finance_reports", actions: ["view"] },
      { moduleId: "finance_overrides", actions: ["view"] },
      // Integrations: read-only — status, scopes, runs, conflicts, audit.
      { moduleId: "integration_catalog", actions: ["view"] },
      { moduleId: "integration_connections", actions: ["view"] },
      { moduleId: "integration_scopes", actions: ["view"] },
      { moduleId: "integration_policies", actions: ["view"] },
      { moduleId: "integration_sync", actions: ["view"] },
      { moduleId: "integration_conflicts", actions: ["view"] },
      { moduleId: "integration_webhooks", actions: ["view"] },
      { moduleId: "integration_outbound_webhooks", actions: ["view"] },
      { moduleId: "integration_logs", actions: ["view"] },
      { moduleId: "integration_audit", actions: ["view"] },
      // Backend Phase 9 — AI. Read-only AI governance: policies, usage, evaluations and audit. Cannot confirm actions.
      { moduleId: "ai_providers", actions: ["view"] },
      { moduleId: "ai_models", actions: ["view"] },
      { moduleId: "ai_routing", actions: ["view"] },
      { moduleId: "ai_policies", actions: ["view"] },
      { moduleId: "ai_usage", actions: ["view_own","view_organization"] },
      { moduleId: "ai_budgets", actions: ["view"] },
      { moduleId: "ai_actions", actions: ["view"] },
      { moduleId: "ai_evaluations", actions: ["view"] },
      { moduleId: "ai_audit", actions: ["view"] },
      // Backend Phase 10 — AI Copilot. Reviews Copilot conversations and tool events (audited); cannot use it to act.
      { moduleId: "ai_copilot_conversations", actions: ["view_audit_history"] },
      { moduleId: "ai_copilot_tools", actions: ["view"] },
    ],
  },
  {
    key: "user", name: "Standard Employee", defaultScope: "Own", purpose: "Provides ordinary employee self-service.",
    permissionGrants: [
      // Own/Assigned-scoped (see defaultScope above) — a Sales
      // Representative sees and edits only records they own, are
      // assigned to, or are explicitly shared with, per the spec.
      { moduleId: "leads", actions: ["view", "create", "edit"] },
      { moduleId: "contacts", actions: ["view", "create", "edit"] },
      { moduleId: "companies", actions: ["view", "create", "edit"] },
      { moduleId: "activities", actions: ["view", "create", "edit"] },
      { moduleId: "notes", actions: ["view", "create", "edit"] },
      { moduleId: "tags", actions: ["view", "edit"] },
      // Sales Representative-equivalent: may create/edit/submit their own
      // Deals and Quotes, but must not approve a Quote (separation of
      // duties is enforced in code regardless, but this role also never
      // gets the "approve" grant at all) and must not confirm Orders or
      // activate/terminate Contracts.
      { moduleId: "pipeline", actions: ["view"] },
      { moduleId: "deals", actions: ["view", "create", "edit", "transition", "close", "reopen"] },
      { moduleId: "products_services", actions: ["view"] },
      { moduleId: "price_books", actions: ["view"] },
      { moduleId: "quotes", actions: ["view", "create", "edit", "submit", "accept", "cancel"] },
      { moduleId: "orders", actions: ["view", "create", "edit"] },
      { moduleId: "contracts", actions: ["view"] },
      { moduleId: "sales_reports", actions: ["view"] },
      // Agent-equivalent: works tickets they created, are assigned, follow or see through a queue.
      { moduleId: "tickets", actions: ["view", "create", "edit", "transition", "resolve", "close", "reply", "escalate", "view_internal_notes", "add_internal_notes"] },
      { moduleId: "support_inboxes", actions: ["view"] },
      { moduleId: "support_queues", actions: ["view"] },
      { moduleId: "knowledge_base", actions: ["view", "create"] },
      { moduleId: "canned_responses", actions: ["view"] },
      // Contributor-equivalent: works assigned tasks, logs and submits own time.
      { moduleId: "projects", actions: ["view"] },
      { moduleId: "tasks", actions: ["view", "create", "edit", "transition"] },
      { moduleId: "project_time", actions: ["view_own", "create", "submit"] },
      { moduleId: "deliverables", actions: ["view", "edit"] },
      { moduleId: "project_risks", actions: ["view"] },
      { moduleId: "project_issues", actions: ["view", "edit"] },
      { moduleId: "change_requests", actions: ["view", "create"] },
      { moduleId: "project_baselines", actions: ["view"] },
      // Submits and tracks their own expenses; no access to invoices.
      { moduleId: "expenses", actions: ["view", "create", "submit"] },
      // Integrations: personal connections only, when policy allows; never shared organization-wide.
      { moduleId: "integration_catalog", actions: ["view"] },
      { moduleId: "integration_connections", actions: ["view", "create_user", "reauthorize", "disconnect"] },
      { moduleId: "integration_scopes", actions: ["view"] },
      { moduleId: "integration_sync", actions: ["view", "configure", "preview", "execute", "cancel"] },
      { moduleId: "integration_conflicts", actions: ["view"] },
      { moduleId: "integration_webhooks", actions: ["view"] },
      // Backend Phase 9 — AI. Uses AI features on records they can access; confirms their own action proposals.
      { moduleId: "ai_usage", actions: ["view_own"] },
      { moduleId: "ai_features", actions: ["use"] },
      { moduleId: "ai_actions", actions: ["view","propose","confirm"] },
      // Backend Phase 10 — AI Copilot. Copilot on the records they can already see.
      { moduleId: "ai_copilot", actions: ["use"] },
      { moduleId: "ai_copilot_conversations", actions: ["view_own"] },
      { moduleId: "ai_copilot_memory", actions: ["configure"] },
      { moduleId: "ai_copilot_tools", actions: ["view"] },
      { moduleId: "ai_copilot_workflows", actions: ["execute"] },
    ],
  },
  {
    key: "finance_manager", name: "Finance Manager", defaultScope: "Organization", purpose: "Approves and posts financial records, closes periods, approves budgets and reconciliations.",
    permissionGrants: [
      // Backend Phase 6 (full spec)
      { moduleId: "invoices", actions: ["view", "approve", "post", "issue", "cancel", "view_audit_history"] },
      { moduleId: "credit_notes", actions: ["view", "approve", "post"] },
      { moduleId: "payments", actions: ["view", "approve", "post", "reverse", "allocate"] },
      { moduleId: "expenses", actions: ["view", "approve", "reject", "approve_exception", "post", "reimburse", "view_audit_history"] },
      { moduleId: "recurring_invoices", actions: ["view"] },
      { moduleId: "finance_configuration", actions: ["view", "configure", "approve"] },
      { moduleId: "fiscal_periods", actions: ["view", "close", "reopen", "post"] },
      { moduleId: "ledger_accounts", actions: ["view", "configure"] },
      { moduleId: "journals", actions: ["view", "approve", "post", "reverse"] },
      { moduleId: "vendors", actions: ["view"] },
      { moduleId: "bills", actions: ["view", "approve", "post", "cancel"] },
      { moduleId: "financial_accounts", actions: ["view", "view_sensitive_fields"] },
      { moduleId: "reconciliation", actions: ["view", "approve"] },
      { moduleId: "budgets", actions: ["view", "approve", "activate"] },
      { moduleId: "finance_reports", actions: ["view"] },
      { moduleId: "finance_overrides", actions: ["view"] },
      // Integrations: finance import sync (read-only providers).
      { moduleId: "integration_catalog", actions: ["view"] },
      { moduleId: "integration_connections", actions: ["view"] },
      { moduleId: "integration_scopes", actions: ["view"] },
      { moduleId: "integration_sync", actions: ["view", "configure", "preview", "execute", "cancel"] },
      { moduleId: "integration_conflicts", actions: ["view", "resolve"] },
      { moduleId: "integration_logs", actions: ["view"] },
      // Backend Phase 9 — AI. Reviews AI usage and manages AI budgets.
      { moduleId: "ai_usage", actions: ["view_own","view_organization"] },
      { moduleId: "ai_budgets", actions: ["view","configure"] },
      { moduleId: "ai_features", actions: ["use"] },
      { moduleId: "ai_actions", actions: ["view","propose","confirm"] },
      // Backend Phase 10 — AI Copilot. Copilot, including sensitive Finance reads (with confirmation).
      { moduleId: "ai_copilot", actions: ["use"] },
      { moduleId: "ai_copilot_conversations", actions: ["view_own"] },
      { moduleId: "ai_copilot_memory", actions: ["configure"] },
      { moduleId: "ai_copilot_tools", actions: ["view","view_sensitive_fields"] },
      { moduleId: "ai_copilot_workflows", actions: ["execute"] },
    ],
  },
  {
    key: "accountant", name: "Accountant", defaultScope: "Organization", purpose: "Prepares journals, invoices, bills and payments, and prepares reconciliations.",
    permissionGrants: [
      // Backend Phase 6 (full spec)
      { moduleId: "invoices", actions: ["view", "create", "edit", "submit", "post", "issue"] },
      { moduleId: "credit_notes", actions: ["view", "create", "post"] },
      { moduleId: "payments", actions: ["view", "create", "post", "allocate"] },
      { moduleId: "expenses", actions: ["view", "post", "reimburse"] },
      { moduleId: "recurring_invoices", actions: ["view", "create", "edit"] },
      { moduleId: "finance_configuration", actions: ["view"] },
      { moduleId: "fiscal_periods", actions: ["view", "close"] },
      { moduleId: "ledger_accounts", actions: ["view", "configure"] },
      { moduleId: "journals", actions: ["view", "create", "post"] },
      { moduleId: "vendors", actions: ["view", "configure"] },
      { moduleId: "bills", actions: ["view", "create", "edit", "submit", "post"] },
      { moduleId: "financial_accounts", actions: ["view", "configure", "view_sensitive_fields"] },
      { moduleId: "reconciliation", actions: ["view", "create"] },
      { moduleId: "budgets", actions: ["view", "create"] },
      { moduleId: "finance_reports", actions: ["view"] },
      // Integrations: preview and run finance imports.
      { moduleId: "integration_catalog", actions: ["view"] },
      { moduleId: "integration_connections", actions: ["view"] },
      { moduleId: "integration_scopes", actions: ["view"] },
      { moduleId: "integration_sync", actions: ["view", "preview", "execute"] },
      { moduleId: "integration_conflicts", actions: ["view"] },
      // Backend Phase 9 — AI. Uses AI features on records they can access.
      { moduleId: "ai_usage", actions: ["view_own"] },
      { moduleId: "ai_features", actions: ["use"] },
      { moduleId: "ai_actions", actions: ["view","propose","confirm"] },
      // Backend Phase 10 — AI Copilot. Copilot on the records they can already see.
      { moduleId: "ai_copilot", actions: ["use"] },
      { moduleId: "ai_copilot_conversations", actions: ["view_own"] },
      { moduleId: "ai_copilot_memory", actions: ["configure"] },
      { moduleId: "ai_copilot_tools", actions: ["view"] },
      { moduleId: "ai_copilot_workflows", actions: ["execute"] },
    ],
  },
];
// Creates any missing built-in role and refreshes the grants of existing
// ones (matched by key). Never touches custom roles or role assignments.
export async function upsertBuiltInRoles(prisma) {
  const roles = {};
  for (const def of BUILT_IN_ROLES) {
    roles[def.key] = await prisma.role.upsert({
      where: { key: def.key },
      update: { permissionGrants: def.permissionGrants },
      create: { ...def, type: "Built-in", isBuiltIn: true, allowedScopes: [def.defaultScope], status: "Active" },
    });
  }
  return roles;
}
