// Backend Phase 13 — disaster-recovery plan catalog (seeded as Draft; an
// approver reviews each). RPO/RTO values are planning targets. The platform
// runs on ONE host with ONE database: several scenarios below recover by
// rebuilding on a new host from off-host backups, not by failing over.
const SINGLE_HOST = "Single host and single database: there is no standby to fail over to. Recovery means rebuilding on a replacement host from off-host backups; expect downtime for the rebuild.";
const plan = (key, title, severity, owner, o) => ({ key, title, severity, incidentOwnerRole: owner, participants: o.participants || ["Incident owner", "Platform operations", "Security administrator"], rpoTargetMinutes: o.rpo ?? 15, rtoTargetMinutes: o.rto ?? 240, singleHostNotes: o.single ?? null, postIncidentReview: o.review || "Blameless review within 5 business days: timeline, root cause, what detection missed, actions with owners and dates.", ...o.body });

export const DR_PLANS = [
  plan("server_loss", "Complete server loss", "SEV-1", "Platform operations lead", { rto: 480, single: SINGLE_HOST, body: {
    detection: "External uptime check and API-unavailable alert; host unreachable over SSH.",
    containment: "Declare a disaster; point the maintenance page at a static host if DNS allows; stop any partially running copies to avoid split writes.",
    evidence: "Provider incident ID, last monitoring data, last backup and WAL archive times from the off-host repository.",
    recoverySteps: ["Provision a replacement host from the host baseline (runbook 01).", "Install Docker (runbook 23) and restore secrets from the secret store — never from backups.", "Deploy the last known-good release by digest (runbook 06) without migrations.", "Restore PostgreSQL from the off-host repository to the latest point (runbook 05).", "Restore object storage and configuration (runbook 07).", "Re-issue TLS certificates (runbook 04) and update DNS after approval.", "Run post-restore validation and smoke tests."],
    backupRequirements: "Off-host pgBackRest repository with WAL, off-host object and configuration copies, secret store reachable without the lost host.",
    communication: "Status page and customer notice at declaration, every 60 minutes, and at restoration.",
    validation: "Migration version matches the release, sign-in works, tenant counts match the last health snapshot, background jobs run, audit trail continuous up to the recovery point.",
    returnToService: "All validation passes, approver signs off, monitoring and backups active on the new host.",
  } }),
  plan("postgres_corruption", "PostgreSQL corruption", "SEV-1", "Platform operations lead", { rto: 240, single: SINGLE_HOST, body: {
    detection: "Checksum or I/O errors in the database log, failed queries, pgBackRest verify failures.",
    containment: "Stop api and worker writes (maintenance mode); preserve the damaged data directory — do not run repair tools on the only copy.",
    evidence: "Database logs, pg_stat_database checksum failures, copy of the damaged volume if disk space allows.",
    recoverySteps: ["Plan an isolated restore to the latest consistent point and validate it (runbook 05).", "Get approval for the production recovery plan.", "Restore into a new volume, switch the db service to it, keep the damaged volume.", "Run validation, then leave maintenance mode."],
    backupRequirements: "Verified base backup and continuous WAL covering the recovery window.",
    communication: "Maintenance notice; incident updates hourly.", validation: "As for any restore plus a full pgBackRest verify on the new primary.",
    returnToService: "Validation passed and a fresh full backup has completed on the recovered database.",
  } }),
  plan("destructive_migration", "Accidental destructive migration", "SEV-1", "Deployment operator", { rto: 240, body: {
    detection: "Migration failure or post-deploy smoke tests showing missing data; error-rate alert after deploy.",
    containment: "Stop the deployment; do not auto-downgrade. Put the app in maintenance mode if data is being lost or corrupted.",
    evidence: "Deployment events, migration logs, the migration SQL, deployment plan and approvals.",
    recoverySteps: ["Mark the deployment Manual Recovery Required.", "Determine the last good point (the pre-migration backup or timestamp).", "Restore to an isolated target at that point and compare (runbook 05).", "Choose: roll-forward fix, or approved PITR to just before the migration.", "Redeploy the previous compatible release by digest."],
    backupRequirements: "Pre-deployment backup checkpoint (deployment gate) and WAL.", communication: "Change record and customer notice if data changed.",
    validation: "Schema matches the target release; data spot checks pass.", returnToService: "Approved release running, backups current.",
  } }),
  plan("bulk_deletion", "Accidental bulk deletion", "SEV-2", "Platform operations lead", { rto: 480, body: {
    detection: "Audit trail shows bulk delete/archive; customer report; sudden drop in tenant counts.",
    containment: "Revoke the actor's sessions if misuse is suspected; pause integrations that might sync deletions outward.",
    evidence: "Audit events with correlation IDs, actor, time window.",
    recoverySteps: ["PITR to just before the deletion into an ISOLATED target.", "Extract only the affected tenant's rows with a reviewed script.", "Re-insert through an approved change; never overwrite the live database for a partial loss."],
    backupRequirements: "WAL covering the deletion time.", communication: "Tenant administrator informed; data-protection review if personal data.",
    validation: "Tenant verifies restored records; audit trail records the restore.", returnToService: "Tenant confirmation and change closed.",
  } }),
  plan("object_storage_loss", "Object-storage loss", "SEV-2", "Platform operations lead", { rto: 480, body: {
    detection: "Object-storage errors, missing files reported, storage health check failing.",
    containment: "Stop writes to the affected bucket; keep versions.",
    evidence: "Storage logs, bucket versioning history.",
    recoverySteps: ["Restore from the versioned off-host bucket copy (runbook 07).", "Re-check database file references against restored objects."],
    backupRequirements: "Versioned off-host object copy.", communication: "Affected tenants informed.",
    validation: "Reference check: every stored file reference resolves.", returnToService: "No missing references.",
  } }),
  plan("redis_loss", "Redis loss", "SEV-3", "Platform operations lead", { rpo: 0, rto: 60, body: {
    detection: "Redis health check failing; readiness shows redis unavailable.",
    containment: "Restart the redis service; the API keeps serving reads where possible.",
    evidence: "Container logs and restart counts.",
    recoverySteps: ["Restart or recreate the redis container (no persistent data is kept by design).", "The transactional outbox re-enqueues pending emails; rate-limit counters reset.", "Confirm workers reconnect."],
    backupRequirements: "None: Redis holds only queues and counters rebuilt from PostgreSQL.", communication: "Internal only unless prolonged.",
    validation: "Queue depth drains; outbox has no stuck events.", returnToService: "Readiness healthy.",
  } }),
  plan("queue_backlog", "Queue backlog or worker failure", "SEV-3", "Platform operations lead", { rpo: 0, rto: 60, body: {
    detection: "Worker-heartbeat and queue-delay alerts.",
    containment: "Stop producers of the failing job type if one is looping.",
    evidence: "Worker logs by correlation ID, dead-letter records.",
    recoverySteps: ["Restart the worker; jobs resume from their leases and checkpoints.", "Retry dead-letter jobs after fixing the cause."],
    backupRequirements: "None.", communication: "Internal.", validation: "Queue delay under threshold; heartbeat fresh.", returnToService: "Alerts resolved.",
  } }),
  plan("ransomware", "Ransomware", "SEV-0", "Security administrator", { rto: 720, single: SINGLE_HOST, body: {
    detection: "Encrypted or renamed files, ransom notes, sudden integrity failures, unexpected admin logins.",
    containment: "Isolate the host from the network (keep it powered for evidence); revoke all credentials; do not pay or negotiate without legal counsel.",
    evidence: "Disk snapshot, system and audit logs, access logs, backup repository access logs.",
    recoverySteps: ["Treat the host and every secret on it as compromised.", "Rebuild on a clean host from the baseline.", "Rotate every secret (emergency runbook).", "Restore from immutable/off-host backups taken before the compromise; verify them in isolation first.", "Harden the entry point before reconnecting."],
    backupRequirements: "Off-host copies the compromised host can't delete (object lock / write-only credentials).", communication: "Legal, leadership, customers and regulators as required.",
    validation: "Clean-host verification, integrity checks, fresh credentials in use.", returnToService: "Security administrator and leadership sign-off.",
  } }),
  plan("admin_credentials_compromised", "Compromised administrative credentials", "SEV-1", "Security administrator", { rto: 120, body: {
    detection: "Privileged-login failure alerts, unusual permission changes, impossible travel, user report.",
    containment: "Suspend the account, revoke all its sessions, rotate any secrets it could read.",
    evidence: "Audit events for the account, session list, IPs.",
    recoverySteps: ["Review every change made by the account and revert as needed.", "Reset credentials with verified identity; require MFA."],
    backupRequirements: "PITR only if data was destroyed.", communication: "Security incident process.",
    validation: "No unexplained changes remain.", returnToService: "Account restored with MFA or removed.",
  } }),
  plan("signing_key_compromised", "Compromised signing key", "SEV-1", "Security administrator", { rpo: 0, rto: 60, body: {
    detection: "Tokens seen that weren't issued, secret found in a repository or log, secret scanner finding.",
    containment: "Rotate JWT_SECRET immediately WITHOUT an overlap window (every session re-authenticates).",
    evidence: "Where the key was exposed; access logs for forged tokens.",
    recoverySteps: ["Emergency rotation runbook: new secret, no JWT_SECRET_PREVIOUS, restart api.", "Revoke all refresh sessions.", "Review actions taken with suspicious tokens."],
    backupRequirements: "None.", communication: "Users told to sign in again.", validation: "Old tokens rejected.", returnToService: "Secret inventory shows the new version.",
  } }),
  plan("integration_credential_compromised", "Compromised integration credential", "SEV-2", "Integration administrator", { rpo: 0, rto: 120, body: {
    detection: "Provider alert, unexpected sync activity, webhook signature failures.",
    containment: "Revoke the connection's token at the provider and disconnect it.",
    evidence: "Integration logs, sync runs, audit events.",
    recoverySteps: ["Reconnect with fresh credentials.", "If the vault master key may be exposed, rotate INTEGRATIONS_KEYS and re-encrypt."],
    backupRequirements: "None.", communication: "Affected tenant.", validation: "Syncs succeed with the new credential.", returnToService: "Connection healthy.",
  } }),
  plan("dns_failure", "DNS failure", "SEV-2", "Platform operations lead", { rpo: 0, rto: 240, body: {
    detection: "External checks fail by name but succeed by IP.",
    containment: "Confirm the registrar and DNS provider status.",
    evidence: "DNS query results, provider status page.",
    recoverySteps: ["Restore records from the documented DNS record list.", "Lower TTLs before planned changes."],
    backupRequirements: "Documented DNS records in the configuration backup.", communication: "Status page on a separate domain if available.", validation: "Resolution from multiple networks.", returnToService: "Checks green.",
  } }),
  plan("tls_failure", "TLS certificate failure", "SEV-2", "Platform operations lead", { rpo: 0, rto: 120, body: {
    detection: "Certificate-expiry alert, browser errors.",
    containment: "None needed beyond renewal; never disable TLS.",
    evidence: "Certificate chain, renewal logs.",
    recoverySteps: ["Renew or re-issue (runbook 04); reload the proxy."],
    backupRequirements: "Certificate metadata in the configuration backup (never private keys in general backups).", communication: "Status page if users are affected.", validation: "Valid chain and expiry > 30 days.", returnToService: "Alert resolved.",
  } }),
  plan("proxy_failure", "Reverse-proxy failure", "SEV-2", "Platform operations lead", { rpo: 0, rto: 60, body: {
    detection: "Public checks fail while internal readiness is healthy.",
    containment: "Roll back the proxy configuration to the previous version.",
    evidence: "Proxy logs and the config diff.",
    recoverySteps: ["Reverse-proxy rollback runbook: restore the previous config, validate (nginx -t), reload."],
    backupRequirements: "Proxy config in version control and the configuration backup.", communication: "Status page.", validation: "HTTPS, headers and SSE work.", returnToService: "Checks green.",
  } }),
  plan("provider_outage", "Hosting provider outage", "SEV-1", "Platform operations lead", { rto: 480, single: SINGLE_HOST, body: {
    detection: "Provider status page and total loss of reachability.",
    containment: "Decide at 60 minutes whether to wait or rebuild elsewhere.",
    evidence: "Provider incident timeline.",
    recoverySteps: ["If rebuilding: follow the complete server loss plan in another location."],
    backupRequirements: "Off-host copies stored with a different provider or region.", communication: "Customer notice.", validation: "As server loss.", returnToService: "As server loss.",
  } }),
  plan("payment_outage", "Payment-provider outage", "SEV-3", "Finance administrator", { rpo: 0, rto: 1440, body: {
    detection: "Payment failures (no live payment provider is connected yet).",
    containment: "Queue payment actions; never retry charges blindly.",
    evidence: "Provider status and failed request IDs.",
    recoverySteps: ["Resume queued work when the provider recovers; reconcile against provider records."],
    backupRequirements: "None.", communication: "Finance team.", validation: "Reconciliation matches.", returnToService: "Provider healthy.",
  } }),
  plan("email_outage", "Email-provider outage", "SEV-3", "Platform operations lead", { rpo: 0, rto: 1440, body: {
    detection: "Outbox events failing; mailer readiness unavailable (informational — the API stays in service).",
    containment: "Outbox keeps events; nothing is lost.",
    evidence: "Outbox failures.",
    recoverySteps: ["Switch SMTP credentials to the secondary provider if configured, or wait; re-drain failed events."],
    backupRequirements: "None.", communication: "Users told invitation and reset emails are delayed.", validation: "Outbox drains.", returnToService: "No failed events pending.",
  } }),
  plan("ai_outage", "AI-provider outage", "SEV-3", "AI administrator", { rpo: 0, rto: 1440, body: {
    detection: "AI failure-rate alerts in AI Monitoring.",
    containment: "Kill switch or fallback routing; deterministic features keep working.",
    evidence: "AI request logs (metadata only).",
    recoverySteps: ["Route to a secondary provider where approved; otherwise wait."],
    backupRequirements: "None.", communication: "In-app notice.", validation: "Failure rate normal.", returnToService: "Kill switch released.",
  } }),
  plan("backup_storage_outage", "Backup-storage outage", "SEV-2", "Backup operator", { rpo: 15, rto: 240, body: {
    detection: "Backup-failed and WAL-archive-lag alerts; repository unreachable.",
    containment: "WAL keeps accumulating locally — watch disk space; do not delete WAL to free space.",
    evidence: "Agent results and storage provider status.",
    recoverySteps: ["Restore access or switch to the secondary repository.", "Run a full backup once available and verify it."],
    backupRequirements: "Two repositories (primary volume and off-host).", communication: "Internal; risk register updated.", validation: "Archive lag back under target; fresh verified backup.", returnToService: "Backups current.",
  } }),
  plan("regional_outage", "Regional or data-center outage", "SEV-0", "Platform operations lead", { rto: 1440, single: `${SINGLE_HOST} There is no multi-region deployment; a second backup location does not make the application highly available.`, body: {
    detection: "Provider regional status; total loss of reachability.",
    containment: "Declare a disaster; decide on relocation.",
    evidence: "Provider timeline.",
    recoverySteps: ["Rebuild in another region from off-region backups (server-loss plan).", "Update DNS after approval."],
    backupRequirements: "Off-region backup copies.", communication: "Customer and leadership notice.", validation: "As server loss.", returnToService: "As server loss.",
  } }),
];
